-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity radix2_32out is
port (
    Ar : IN STD_LOGIC_VECTOR (15 downto 0);
    Ai : IN STD_LOGIC_VECTOR (15 downto 0);
    Br : IN STD_LOGIC_VECTOR (15 downto 0);
    Bi : IN STD_LOGIC_VECTOR (15 downto 0);
    Wr : IN STD_LOGIC_VECTOR (15 downto 0);
    Wi : IN STD_LOGIC_VECTOR (15 downto 0);
    Cr : OUT STD_LOGIC_VECTOR (31 downto 0);
    Dr : OUT STD_LOGIC_VECTOR (31 downto 0);
    Ci : OUT STD_LOGIC_VECTOR (31 downto 0);
    Di : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of radix2_32out is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "radix2_32out_radix2_32out,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.937000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=166,HLS_VERSION=2025_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal m1_fu_118_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln34_1_fu_114_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal m1_fu_118_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln34_fu_110_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln40_fu_132_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln35_1_fu_128_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln40_fu_132_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_170_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln42_fu_138_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_180_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln45_fu_154_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_170_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_170_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln35_fu_124_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal m1_fu_118_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_180_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln40_fu_132_p2 : STD_LOGIC_VECTOR (31 downto 0);

    component radix2_32out_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component radix2_32out_mac_mulsub_16s_16s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component radix2_32out_mac_muladd_16s_16s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mul_16s_16s_32_1_1_U1 : component radix2_32out_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => m1_fu_118_p0,
        din1 => m1_fu_118_p1,
        dout => m1_fu_118_p2);

    mul_16s_16s_32_1_1_U2 : component radix2_32out_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => mul_ln40_fu_132_p0,
        din1 => mul_ln40_fu_132_p1,
        dout => mul_ln40_fu_132_p2);

    mac_mulsub_16s_16s_32s_32_1_1_U3 : component radix2_32out_mac_mulsub_16s_16s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_170_p0,
        din1 => grp_fu_170_p1,
        din2 => m1_fu_118_p2,
        dout => grp_fu_170_p3);

    mac_muladd_16s_16s_32s_32_1_1_U4 : component radix2_32out_mac_muladd_16s_16s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => grp_fu_180_p0,
        din1 => grp_fu_180_p1,
        din2 => mul_ln40_fu_132_p2,
        dout => grp_fu_180_p3);




    Ci <= std_logic_vector(signed(grp_fu_180_p3) + signed(sext_ln45_fu_154_p1));
    Cr <= std_logic_vector(signed(grp_fu_170_p3) + signed(sext_ln42_fu_138_p1));
    Di <= std_logic_vector(signed(sext_ln45_fu_154_p1) - signed(grp_fu_180_p3));
    Dr <= std_logic_vector(signed(sext_ln42_fu_138_p1) - signed(grp_fu_170_p3));
    grp_fu_170_p0 <= sext_ln35_1_fu_128_p1(16 - 1 downto 0);
    grp_fu_170_p1 <= sext_ln35_fu_124_p1(16 - 1 downto 0);
    grp_fu_180_p0 <= sext_ln34_1_fu_114_p1(16 - 1 downto 0);
    grp_fu_180_p1 <= sext_ln35_fu_124_p1(16 - 1 downto 0);
    m1_fu_118_p0 <= sext_ln34_1_fu_114_p1(16 - 1 downto 0);
    m1_fu_118_p1 <= sext_ln34_fu_110_p1(16 - 1 downto 0);
    mul_ln40_fu_132_p0 <= sext_ln35_1_fu_128_p1(16 - 1 downto 0);
    mul_ln40_fu_132_p1 <= sext_ln34_fu_110_p1(16 - 1 downto 0);
        sext_ln34_1_fu_114_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Wr),32));

        sext_ln34_fu_110_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Br),32));

        sext_ln35_1_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Wi),32));

        sext_ln35_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Bi),32));

        sext_ln42_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ar),32));

        sext_ln45_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ai),32));

end behav;
