-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_HAB_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 16; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 33
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_HAB_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1111111111111111", 1 => "0000000100000001", 2 => "0001000000010000", 3 => "0000010000000100", 
    4 => "0100000001000000", 5 => "0000001000000010", 6 => "0010000000100000", 7 => "0000100000001000", 
    8 => "1000000010000000", 9 => "0000000000010001", 10 => "0001000100000000", 11 => "0000000001000100", 
    12 => "0100010000000000", 13 => "0000000000100010", 14 => "0010001000000000", 15 => "0000000010001000", 
    16 => "1000100000000000", 17 => "0000000000000101", 18 => "0000010100000000", 19 => "0000000001010000", 
    20 => "0101000000000000", 21 => "0000000000001010", 22 => "0000101000000000", 23 => "0000000010100000", 
    24 => "1010000000000000", 25 => "0000000000000011", 26 => "0000001100000000", 27 => "0000000000110000", 
    28 => "0011000000000000", 29 => "0000000000001100", 30 => "0000110000000000", 31 => "0000000011000000", 
    32 => "1100000000000000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

