-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft16_hls is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Xr_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    Xr_ce0 : OUT STD_LOGIC;
    Xr_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    Xr_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    Xr_ce1 : OUT STD_LOGIC;
    Xr_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    Xi_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    Xi_ce0 : OUT STD_LOGIC;
    Xi_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    Xi_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    Xi_ce1 : OUT STD_LOGIC;
    Xi_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    outRe_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    outRe_ce0 : OUT STD_LOGIC;
    outRe_we0 : OUT STD_LOGIC;
    outRe_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    outRe_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    outRe_ce1 : OUT STD_LOGIC;
    outRe_we1 : OUT STD_LOGIC;
    outRe_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    outIm_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    outIm_ce0 : OUT STD_LOGIC;
    outIm_we0 : OUT STD_LOGIC;
    outIm_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    outIm_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    outIm_ce1 : OUT STD_LOGIC;
    outIm_we1 : OUT STD_LOGIC;
    outIm_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fft16_hls is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fft16_hls_fft16_hls,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.793000,HLS_SYN_LAT=153,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2605,HLS_SYN_LUT=2820,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (17 downto 0) := "000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (17 downto 0) := "000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (17 downto 0) := "000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (17 downto 0) := "000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (17 downto 0) := "000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (17 downto 0) := "000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (17 downto 0) := "000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (17 downto 0) := "001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (17 downto 0) := "010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv64_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001011";
    constant ap_const_lv64_C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001100";
    constant ap_const_lv64_D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001101";
    constant ap_const_lv64_E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001110";
    constant ap_const_lv64_F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Xr_load_reg_1262 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal Xi_load_reg_1267 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_1_reg_1272 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xi_load_1_reg_1277 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_2_reg_1302 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal Xi_load_2_reg_1307 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_3_reg_1312 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xi_load_3_reg_1317 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_4_reg_1342 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal Xi_load_4_reg_1347 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_5_reg_1352 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xi_load_5_reg_1357 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_6_reg_1382 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal Xi_load_6_reg_1387 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_7_reg_1392 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xi_load_7_reg_1397 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_8_reg_1422 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal Xi_load_8_reg_1427 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_9_reg_1432 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xi_load_9_reg_1437 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_10_reg_1462 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal Xi_load_10_reg_1467 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_11_reg_1472 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xi_load_11_reg_1477 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_12_reg_1502 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal Xi_load_12_reg_1507 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_13_reg_1512 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xi_load_13_reg_1517 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_14_reg_1542 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal Xi_load_14_reg_1547 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xr_load_15_reg_1552 : STD_LOGIC_VECTOR (15 downto 0);
    signal Xi_load_15_reg_1557 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_idle : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_ready : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out_ap_vld : STD_LOGIC;
    signal grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal nextRe_loc_fu_208 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_16_loc_fu_204 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_32_loc_fu_200 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_17_loc_fu_196 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_33_loc_fu_192 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_18_loc_fu_188 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_34_loc_fu_184 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_19_loc_fu_180 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_35_loc_fu_176 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_20_loc_fu_172 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_36_loc_fu_168 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_21_loc_fu_164 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_37_loc_fu_160 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_22_loc_fu_156 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_38_loc_fu_152 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_23_loc_fu_148 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_39_loc_fu_144 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_24_loc_fu_140 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_40_loc_fu_136 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_25_loc_fu_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_41_loc_fu_128 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_26_loc_fu_124 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_42_loc_fu_120 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_27_loc_fu_116 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_43_loc_fu_112 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_28_loc_fu_108 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_44_loc_fu_104 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_29_loc_fu_100 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_45_loc_fu_96 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_30_loc_fu_92 : STD_LOGIC_VECTOR (15 downto 0);
    signal nextRe_46_loc_fu_88 : STD_LOGIC_VECTOR (15 downto 0);
    signal Im_31_loc_fu_84 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal Xr_ce1_local : STD_LOGIC;
    signal Xr_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal Xr_ce0_local : STD_LOGIC;
    signal Xr_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal Xi_ce1_local : STD_LOGIC;
    signal Xi_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal Xi_ce0_local : STD_LOGIC;
    signal Xi_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal outRe_we1_local : STD_LOGIC;
    signal outRe_d1_local : STD_LOGIC_VECTOR (15 downto 0);
    signal outRe_ce1_local : STD_LOGIC;
    signal outRe_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal outRe_we0_local : STD_LOGIC;
    signal outRe_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal outRe_ce0_local : STD_LOGIC;
    signal outRe_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal outIm_we1_local : STD_LOGIC;
    signal outIm_d1_local : STD_LOGIC_VECTOR (15 downto 0);
    signal outIm_ce1_local : STD_LOGIC;
    signal outIm_address1_local : STD_LOGIC_VECTOR (3 downto 0);
    signal outIm_we0_local : STD_LOGIC;
    signal outIm_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal outIm_ce0_local : STD_LOGIC;
    signal outIm_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Xr_load_15 : IN STD_LOGIC_VECTOR (15 downto 0);
        Xi_load_15 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_9 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_10 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_11 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_12 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_13 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_14 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_15 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_16 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_17 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_18 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_19 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_20 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_21 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_22 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_23 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_24 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_25 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_26 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_27 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcR_28 : IN STD_LOGIC_VECTOR (15 downto 0);
        srcI_29 : IN STD_LOGIC_VECTOR (15 downto 0);
        nextRe_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_out_ap_vld : OUT STD_LOGIC;
        Im_16_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_16_out_ap_vld : OUT STD_LOGIC;
        nextRe_32_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_32_out_ap_vld : OUT STD_LOGIC;
        Im_17_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_17_out_ap_vld : OUT STD_LOGIC;
        nextRe_33_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_33_out_ap_vld : OUT STD_LOGIC;
        Im_18_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_18_out_ap_vld : OUT STD_LOGIC;
        nextRe_34_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_34_out_ap_vld : OUT STD_LOGIC;
        Im_19_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_19_out_ap_vld : OUT STD_LOGIC;
        nextRe_35_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_35_out_ap_vld : OUT STD_LOGIC;
        Im_20_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_20_out_ap_vld : OUT STD_LOGIC;
        nextRe_36_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_36_out_ap_vld : OUT STD_LOGIC;
        Im_21_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_21_out_ap_vld : OUT STD_LOGIC;
        nextRe_37_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_37_out_ap_vld : OUT STD_LOGIC;
        Im_22_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_22_out_ap_vld : OUT STD_LOGIC;
        nextRe_38_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_38_out_ap_vld : OUT STD_LOGIC;
        Im_23_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_23_out_ap_vld : OUT STD_LOGIC;
        nextRe_39_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_39_out_ap_vld : OUT STD_LOGIC;
        Im_24_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_24_out_ap_vld : OUT STD_LOGIC;
        nextRe_40_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_40_out_ap_vld : OUT STD_LOGIC;
        Im_25_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_25_out_ap_vld : OUT STD_LOGIC;
        nextRe_41_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_41_out_ap_vld : OUT STD_LOGIC;
        Im_26_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_26_out_ap_vld : OUT STD_LOGIC;
        nextRe_42_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_42_out_ap_vld : OUT STD_LOGIC;
        Im_27_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_27_out_ap_vld : OUT STD_LOGIC;
        nextRe_43_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_43_out_ap_vld : OUT STD_LOGIC;
        Im_28_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_28_out_ap_vld : OUT STD_LOGIC;
        nextRe_44_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_44_out_ap_vld : OUT STD_LOGIC;
        Im_29_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_29_out_ap_vld : OUT STD_LOGIC;
        nextRe_45_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_45_out_ap_vld : OUT STD_LOGIC;
        Im_30_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_30_out_ap_vld : OUT STD_LOGIC;
        nextRe_46_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        nextRe_46_out_ap_vld : OUT STD_LOGIC;
        Im_31_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        Im_31_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824 : component fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start,
        ap_done => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done,
        ap_idle => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_idle,
        ap_ready => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_ready,
        Xr_load_15 => Xr_load_15_reg_1552,
        Xi_load_15 => Xi_load_15_reg_1557,
        srcR => Xr_load_reg_1262,
        srcI_1 => Xi_load_reg_1267,
        srcR_2 => Xr_load_1_reg_1272,
        srcI_3 => Xi_load_1_reg_1277,
        srcR_4 => Xr_load_2_reg_1302,
        srcI_5 => Xi_load_2_reg_1307,
        srcR_6 => Xr_load_3_reg_1312,
        srcI_7 => Xi_load_3_reg_1317,
        srcR_8 => Xr_load_4_reg_1342,
        srcI_9 => Xi_load_4_reg_1347,
        srcR_10 => Xr_load_5_reg_1352,
        srcI_11 => Xi_load_5_reg_1357,
        srcR_12 => Xr_load_6_reg_1382,
        srcI_13 => Xi_load_6_reg_1387,
        srcR_14 => Xr_load_7_reg_1392,
        srcI_15 => Xi_load_7_reg_1397,
        srcR_16 => Xr_load_8_reg_1422,
        srcI_17 => Xi_load_8_reg_1427,
        srcR_18 => Xr_load_9_reg_1432,
        srcI_19 => Xi_load_9_reg_1437,
        srcR_20 => Xr_load_10_reg_1462,
        srcI_21 => Xi_load_10_reg_1467,
        srcR_22 => Xr_load_11_reg_1472,
        srcI_23 => Xi_load_11_reg_1477,
        srcR_24 => Xr_load_12_reg_1502,
        srcI_25 => Xi_load_12_reg_1507,
        srcR_26 => Xr_load_13_reg_1512,
        srcI_27 => Xi_load_13_reg_1517,
        srcR_28 => Xr_load_14_reg_1542,
        srcI_29 => Xi_load_14_reg_1547,
        nextRe_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out,
        nextRe_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out_ap_vld,
        Im_16_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out,
        Im_16_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out_ap_vld,
        nextRe_32_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out,
        nextRe_32_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out_ap_vld,
        Im_17_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out,
        Im_17_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out_ap_vld,
        nextRe_33_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out,
        nextRe_33_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out_ap_vld,
        Im_18_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out,
        Im_18_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out_ap_vld,
        nextRe_34_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out,
        nextRe_34_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out_ap_vld,
        Im_19_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out,
        Im_19_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out_ap_vld,
        nextRe_35_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out,
        nextRe_35_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out_ap_vld,
        Im_20_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out,
        Im_20_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out_ap_vld,
        nextRe_36_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out,
        nextRe_36_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out_ap_vld,
        Im_21_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out,
        Im_21_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out_ap_vld,
        nextRe_37_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out,
        nextRe_37_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out_ap_vld,
        Im_22_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out,
        Im_22_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out_ap_vld,
        nextRe_38_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out,
        nextRe_38_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out_ap_vld,
        Im_23_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out,
        Im_23_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out_ap_vld,
        nextRe_39_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out,
        nextRe_39_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out_ap_vld,
        Im_24_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out,
        Im_24_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out_ap_vld,
        nextRe_40_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out,
        nextRe_40_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out_ap_vld,
        Im_25_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out,
        Im_25_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out_ap_vld,
        nextRe_41_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out,
        nextRe_41_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out_ap_vld,
        Im_26_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out,
        Im_26_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out_ap_vld,
        nextRe_42_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out,
        nextRe_42_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out_ap_vld,
        Im_27_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out,
        Im_27_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out_ap_vld,
        nextRe_43_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out,
        nextRe_43_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out_ap_vld,
        Im_28_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out,
        Im_28_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out_ap_vld,
        nextRe_44_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out,
        nextRe_44_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out_ap_vld,
        Im_29_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out,
        Im_29_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out_ap_vld,
        nextRe_45_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out,
        nextRe_45_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out_ap_vld,
        Im_30_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out,
        Im_30_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out_ap_vld,
        nextRe_46_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out,
        nextRe_46_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out_ap_vld,
        Im_31_out => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out,
        Im_31_out_ap_vld => grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_ready = ap_const_logic_1)) then 
                    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_16_loc_fu_204 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_17_loc_fu_196 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_18_loc_fu_188 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_19_loc_fu_180 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_20_loc_fu_172 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_21_loc_fu_164 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_22_loc_fu_156 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_23_loc_fu_148 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_24_loc_fu_140 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_25_loc_fu_132 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_26_loc_fu_124 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_27_loc_fu_116 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_28_loc_fu_108 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_29_loc_fu_100 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_30_loc_fu_92 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                Im_31_loc_fu_84 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                Xi_load_10_reg_1467 <= Xi_q1;
                Xi_load_11_reg_1477 <= Xi_q0;
                Xr_load_10_reg_1462 <= Xr_q1;
                Xr_load_11_reg_1472 <= Xr_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                Xi_load_12_reg_1507 <= Xi_q1;
                Xi_load_13_reg_1517 <= Xi_q0;
                Xr_load_12_reg_1502 <= Xr_q1;
                Xr_load_13_reg_1512 <= Xr_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                Xi_load_14_reg_1547 <= Xi_q1;
                Xi_load_15_reg_1557 <= Xi_q0;
                Xr_load_14_reg_1542 <= Xr_q1;
                Xr_load_15_reg_1552 <= Xr_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                Xi_load_1_reg_1277 <= Xi_q0;
                Xi_load_reg_1267 <= Xi_q1;
                Xr_load_1_reg_1272 <= Xr_q0;
                Xr_load_reg_1262 <= Xr_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                Xi_load_2_reg_1307 <= Xi_q1;
                Xi_load_3_reg_1317 <= Xi_q0;
                Xr_load_2_reg_1302 <= Xr_q1;
                Xr_load_3_reg_1312 <= Xr_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                Xi_load_4_reg_1347 <= Xi_q1;
                Xi_load_5_reg_1357 <= Xi_q0;
                Xr_load_4_reg_1342 <= Xr_q1;
                Xr_load_5_reg_1352 <= Xr_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                Xi_load_6_reg_1387 <= Xi_q1;
                Xi_load_7_reg_1397 <= Xi_q0;
                Xr_load_6_reg_1382 <= Xr_q1;
                Xr_load_7_reg_1392 <= Xr_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                Xi_load_8_reg_1427 <= Xi_q1;
                Xi_load_9_reg_1437 <= Xi_q0;
                Xr_load_8_reg_1422 <= Xr_q1;
                Xr_load_9_reg_1432 <= Xr_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_32_loc_fu_200 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_33_loc_fu_192 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_34_loc_fu_184 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_35_loc_fu_176 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_36_loc_fu_168 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_37_loc_fu_160 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_38_loc_fu_152 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_39_loc_fu_144 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_40_loc_fu_136 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_41_loc_fu_128 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_42_loc_fu_120 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_43_loc_fu_112 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_44_loc_fu_104 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_45_loc_fu_96 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_46_loc_fu_88 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                nextRe_loc_fu_208 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    Xi_address0 <= Xi_address0_local;

    Xi_address0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            Xi_address0_local <= ap_const_lv64_0(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            Xi_address0_local <= ap_const_lv64_E(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            Xi_address0_local <= ap_const_lv64_C(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            Xi_address0_local <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Xi_address0_local <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            Xi_address0_local <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Xi_address0_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            Xi_address0_local <= ap_const_lv64_2(4 - 1 downto 0);
        else 
            Xi_address0_local <= "XXXX";
        end if; 
    end process;

    Xi_address1 <= Xi_address1_local;

    Xi_address1_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            Xi_address1_local <= ap_const_lv64_F(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            Xi_address1_local <= ap_const_lv64_D(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            Xi_address1_local <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            Xi_address1_local <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Xi_address1_local <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            Xi_address1_local <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Xi_address1_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            Xi_address1_local <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            Xi_address1_local <= "XXXX";
        end if; 
    end process;

    Xi_ce0 <= Xi_ce0_local;

    Xi_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            Xi_ce0_local <= ap_const_logic_1;
        else 
            Xi_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    Xi_ce1 <= Xi_ce1_local;

    Xi_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            Xi_ce1_local <= ap_const_logic_1;
        else 
            Xi_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    Xr_address0 <= Xr_address0_local;

    Xr_address0_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            Xr_address0_local <= ap_const_lv64_0(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            Xr_address0_local <= ap_const_lv64_E(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            Xr_address0_local <= ap_const_lv64_C(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            Xr_address0_local <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Xr_address0_local <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            Xr_address0_local <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Xr_address0_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            Xr_address0_local <= ap_const_lv64_2(4 - 1 downto 0);
        else 
            Xr_address0_local <= "XXXX";
        end if; 
    end process;

    Xr_address1 <= Xr_address1_local;

    Xr_address1_local_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            Xr_address1_local <= ap_const_lv64_F(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            Xr_address1_local <= ap_const_lv64_D(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            Xr_address1_local <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            Xr_address1_local <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Xr_address1_local <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            Xr_address1_local <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Xr_address1_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            Xr_address1_local <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            Xr_address1_local <= "XXXX";
        end if; 
    end process;

    Xr_ce0 <= Xr_ce0_local;

    Xr_ce0_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            Xr_ce0_local <= ap_const_logic_1;
        else 
            Xr_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    Xr_ce1 <= Xr_ce1_local;

    Xr_ce1_local_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            Xr_ce1_local <= ap_const_logic_1;
        else 
            Xr_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done)
    begin
        if ((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg;
    outIm_address0 <= outIm_address0_local;

    outIm_address0_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            outIm_address0_local <= ap_const_lv64_F(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            outIm_address0_local <= ap_const_lv64_D(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            outIm_address0_local <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            outIm_address0_local <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            outIm_address0_local <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            outIm_address0_local <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outIm_address0_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            outIm_address0_local <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            outIm_address0_local <= "XXXX";
        end if; 
    end process;

    outIm_address1 <= outIm_address1_local;

    outIm_address1_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            outIm_address1_local <= ap_const_lv64_E(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            outIm_address1_local <= ap_const_lv64_C(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            outIm_address1_local <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            outIm_address1_local <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            outIm_address1_local <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            outIm_address1_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outIm_address1_local <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            outIm_address1_local <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            outIm_address1_local <= "XXXX";
        end if; 
    end process;

    outIm_ce0 <= outIm_ce0_local;

    outIm_ce0_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            outIm_ce0_local <= ap_const_logic_1;
        else 
            outIm_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    outIm_ce1 <= outIm_ce1_local;

    outIm_ce1_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            outIm_ce1_local <= ap_const_logic_1;
        else 
            outIm_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    outIm_d0 <= outIm_d0_local;

    outIm_d0_local_assign_proc : process(Im_24_loc_fu_140, Im_25_loc_fu_132, Im_26_loc_fu_124, Im_27_loc_fu_116, Im_28_loc_fu_108, Im_29_loc_fu_100, Im_30_loc_fu_92, Im_31_loc_fu_84, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            outIm_d0_local <= Im_31_loc_fu_84;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            outIm_d0_local <= Im_27_loc_fu_116;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            outIm_d0_local <= Im_29_loc_fu_100;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            outIm_d0_local <= Im_25_loc_fu_132;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            outIm_d0_local <= Im_30_loc_fu_92;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            outIm_d0_local <= Im_26_loc_fu_124;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outIm_d0_local <= Im_28_loc_fu_108;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            outIm_d0_local <= Im_24_loc_fu_140;
        else 
            outIm_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    outIm_d1 <= outIm_d1_local;

    outIm_d1_local_assign_proc : process(Im_16_loc_fu_204, Im_17_loc_fu_196, Im_18_loc_fu_188, Im_19_loc_fu_180, Im_20_loc_fu_172, Im_21_loc_fu_164, Im_22_loc_fu_156, Im_23_loc_fu_148, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            outIm_d1_local <= Im_23_loc_fu_148;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            outIm_d1_local <= Im_19_loc_fu_180;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            outIm_d1_local <= Im_21_loc_fu_164;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            outIm_d1_local <= Im_17_loc_fu_196;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            outIm_d1_local <= Im_22_loc_fu_156;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            outIm_d1_local <= Im_18_loc_fu_188;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outIm_d1_local <= Im_20_loc_fu_172;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            outIm_d1_local <= Im_16_loc_fu_204;
        else 
            outIm_d1_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    outIm_we0 <= outIm_we0_local;

    outIm_we0_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            outIm_we0_local <= ap_const_logic_1;
        else 
            outIm_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    outIm_we1 <= outIm_we1_local;

    outIm_we1_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            outIm_we1_local <= ap_const_logic_1;
        else 
            outIm_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    outRe_address0 <= outRe_address0_local;

    outRe_address0_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            outRe_address0_local <= ap_const_lv64_F(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            outRe_address0_local <= ap_const_lv64_D(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            outRe_address0_local <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            outRe_address0_local <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            outRe_address0_local <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            outRe_address0_local <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outRe_address0_local <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            outRe_address0_local <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            outRe_address0_local <= "XXXX";
        end if; 
    end process;

    outRe_address1 <= outRe_address1_local;

    outRe_address1_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            outRe_address1_local <= ap_const_lv64_E(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            outRe_address1_local <= ap_const_lv64_C(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            outRe_address1_local <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            outRe_address1_local <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            outRe_address1_local <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            outRe_address1_local <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outRe_address1_local <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            outRe_address1_local <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            outRe_address1_local <= "XXXX";
        end if; 
    end process;

    outRe_ce0 <= outRe_ce0_local;

    outRe_ce0_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            outRe_ce0_local <= ap_const_logic_1;
        else 
            outRe_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    outRe_ce1 <= outRe_ce1_local;

    outRe_ce1_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            outRe_ce1_local <= ap_const_logic_1;
        else 
            outRe_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    outRe_d0 <= outRe_d0_local;

    outRe_d0_local_assign_proc : process(nextRe_39_loc_fu_144, nextRe_40_loc_fu_136, nextRe_41_loc_fu_128, nextRe_42_loc_fu_120, nextRe_43_loc_fu_112, nextRe_44_loc_fu_104, nextRe_45_loc_fu_96, nextRe_46_loc_fu_88, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            outRe_d0_local <= nextRe_46_loc_fu_88;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            outRe_d0_local <= nextRe_42_loc_fu_120;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            outRe_d0_local <= nextRe_44_loc_fu_104;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            outRe_d0_local <= nextRe_40_loc_fu_136;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            outRe_d0_local <= nextRe_45_loc_fu_96;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            outRe_d0_local <= nextRe_41_loc_fu_128;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outRe_d0_local <= nextRe_43_loc_fu_112;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            outRe_d0_local <= nextRe_39_loc_fu_144;
        else 
            outRe_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    outRe_d1 <= outRe_d1_local;

    outRe_d1_local_assign_proc : process(nextRe_loc_fu_208, nextRe_32_loc_fu_200, nextRe_33_loc_fu_192, nextRe_34_loc_fu_184, nextRe_35_loc_fu_176, nextRe_36_loc_fu_168, nextRe_37_loc_fu_160, nextRe_38_loc_fu_152, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            outRe_d1_local <= nextRe_38_loc_fu_152;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            outRe_d1_local <= nextRe_34_loc_fu_184;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            outRe_d1_local <= nextRe_36_loc_fu_168;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            outRe_d1_local <= nextRe_32_loc_fu_200;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            outRe_d1_local <= nextRe_37_loc_fu_160;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            outRe_d1_local <= nextRe_33_loc_fu_192;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outRe_d1_local <= nextRe_35_loc_fu_176;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            outRe_d1_local <= nextRe_loc_fu_208;
        else 
            outRe_d1_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    outRe_we0 <= outRe_we0_local;

    outRe_we0_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            outRe_we0_local <= ap_const_logic_1;
        else 
            outRe_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    outRe_we1 <= outRe_we1_local;

    outRe_we1_local_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            outRe_we1_local <= ap_const_logic_1;
        else 
            outRe_we1_local <= ap_const_logic_0;
        end if; 
    end process;

end behav;
