-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity radix2_baseline is
port (
    Ar : IN STD_LOGIC_VECTOR (15 downto 0);
    Ai : IN STD_LOGIC_VECTOR (15 downto 0);
    Br : IN STD_LOGIC_VECTOR (15 downto 0);
    Bi : IN STD_LOGIC_VECTOR (15 downto 0);
    Wr : IN STD_LOGIC_VECTOR (15 downto 0);
    Wi : IN STD_LOGIC_VECTOR (15 downto 0);
    Cr : OUT STD_LOGIC_VECTOR (15 downto 0);
    Dr : OUT STD_LOGIC_VECTOR (15 downto 0);
    Ci : OUT STD_LOGIC_VECTOR (15 downto 0);
    Di : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of radix2_baseline is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "radix2_baseline_radix2_baseline,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.506000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=102,HLS_VERSION=2025_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal add_ln44_fu_122_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_146_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln45_fu_128_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln48_fu_134_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_156_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln49_fu_140_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln38_fu_110_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln41_1_fu_116_p2 : STD_LOGIC_VECTOR (15 downto 0);

    component radix2_baseline_mul_16s_16s_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component radix2_baseline_mac_mulsub_16s_16s_16ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component radix2_baseline_mac_muladd_16s_16s_16ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    mul_16s_16s_16_1_1_U1 : component radix2_baseline_mul_16s_16s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => Wr,
        din1 => Br,
        dout => mul_ln38_fu_110_p2);

    mul_16s_16s_16_1_1_U2 : component radix2_baseline_mul_16s_16s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => Wi,
        din1 => Br,
        dout => mul_ln41_1_fu_116_p2);

    mac_mulsub_16s_16s_16ns_16_1_1_U3 : component radix2_baseline_mac_mulsub_16s_16s_16ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => Wi,
        din1 => Bi,
        din2 => mul_ln38_fu_110_p2,
        dout => grp_fu_146_p3);

    mac_muladd_16s_16s_16ns_16_1_1_U4 : component radix2_baseline_mac_muladd_16s_16s_16ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => Wr,
        din1 => Bi,
        din2 => mul_ln41_1_fu_116_p2,
        dout => grp_fu_156_p3);




    Ci <= std_logic_vector(signed(add_ln48_fu_134_p0) + signed(Ai));
    Cr <= std_logic_vector(signed(add_ln44_fu_122_p0) + signed(Ar));
    Di <= std_logic_vector(unsigned(Ai) - unsigned(sub_ln49_fu_140_p1));
    Dr <= std_logic_vector(unsigned(Ar) - unsigned(sub_ln45_fu_128_p1));
    add_ln44_fu_122_p0 <= grp_fu_146_p3;
    add_ln48_fu_134_p0 <= grp_fu_156_p3;
    sub_ln45_fu_128_p1 <= grp_fu_146_p3;
    sub_ln49_fu_140_p1 <= grp_fu_156_p3;
end behav;
