// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Xr_load_15,
        Xi_load_15,
        srcR,
        srcI_1,
        srcR_2,
        srcI_3,
        srcR_4,
        srcI_5,
        srcR_6,
        srcI_7,
        srcR_8,
        srcI_9,
        srcR_10,
        srcI_11,
        srcR_12,
        srcI_13,
        srcR_14,
        srcI_15,
        srcR_16,
        srcI_17,
        srcR_18,
        srcI_19,
        srcR_20,
        srcI_21,
        srcR_22,
        srcI_23,
        srcR_24,
        srcI_25,
        srcR_26,
        srcI_27,
        srcR_28,
        srcI_29,
        nextRe_out,
        nextRe_out_ap_vld,
        Im_16_out,
        Im_16_out_ap_vld,
        nextRe_32_out,
        nextRe_32_out_ap_vld,
        Im_17_out,
        Im_17_out_ap_vld,
        nextRe_33_out,
        nextRe_33_out_ap_vld,
        Im_18_out,
        Im_18_out_ap_vld,
        nextRe_34_out,
        nextRe_34_out_ap_vld,
        Im_19_out,
        Im_19_out_ap_vld,
        nextRe_35_out,
        nextRe_35_out_ap_vld,
        Im_20_out,
        Im_20_out_ap_vld,
        nextRe_36_out,
        nextRe_36_out_ap_vld,
        Im_21_out,
        Im_21_out_ap_vld,
        nextRe_37_out,
        nextRe_37_out_ap_vld,
        Im_22_out,
        Im_22_out_ap_vld,
        nextRe_38_out,
        nextRe_38_out_ap_vld,
        Im_23_out,
        Im_23_out_ap_vld,
        nextRe_39_out,
        nextRe_39_out_ap_vld,
        Im_24_out,
        Im_24_out_ap_vld,
        nextRe_40_out,
        nextRe_40_out_ap_vld,
        Im_25_out,
        Im_25_out_ap_vld,
        nextRe_41_out,
        nextRe_41_out_ap_vld,
        Im_26_out,
        Im_26_out_ap_vld,
        nextRe_42_out,
        nextRe_42_out_ap_vld,
        Im_27_out,
        Im_27_out_ap_vld,
        nextRe_43_out,
        nextRe_43_out_ap_vld,
        Im_28_out,
        Im_28_out_ap_vld,
        nextRe_44_out,
        nextRe_44_out_ap_vld,
        Im_29_out,
        Im_29_out_ap_vld,
        nextRe_45_out,
        nextRe_45_out_ap_vld,
        Im_30_out,
        Im_30_out_ap_vld,
        nextRe_46_out,
        nextRe_46_out_ap_vld,
        Im_31_out,
        Im_31_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] Xr_load_15;
input  [15:0] Xi_load_15;
input  [15:0] srcR;
input  [15:0] srcI_1;
input  [15:0] srcR_2;
input  [15:0] srcI_3;
input  [15:0] srcR_4;
input  [15:0] srcI_5;
input  [15:0] srcR_6;
input  [15:0] srcI_7;
input  [15:0] srcR_8;
input  [15:0] srcI_9;
input  [15:0] srcR_10;
input  [15:0] srcI_11;
input  [15:0] srcR_12;
input  [15:0] srcI_13;
input  [15:0] srcR_14;
input  [15:0] srcI_15;
input  [15:0] srcR_16;
input  [15:0] srcI_17;
input  [15:0] srcR_18;
input  [15:0] srcI_19;
input  [15:0] srcR_20;
input  [15:0] srcI_21;
input  [15:0] srcR_22;
input  [15:0] srcI_23;
input  [15:0] srcR_24;
input  [15:0] srcI_25;
input  [15:0] srcR_26;
input  [15:0] srcI_27;
input  [15:0] srcR_28;
input  [15:0] srcI_29;
output  [15:0] nextRe_out;
output   nextRe_out_ap_vld;
output  [15:0] Im_16_out;
output   Im_16_out_ap_vld;
output  [15:0] nextRe_32_out;
output   nextRe_32_out_ap_vld;
output  [15:0] Im_17_out;
output   Im_17_out_ap_vld;
output  [15:0] nextRe_33_out;
output   nextRe_33_out_ap_vld;
output  [15:0] Im_18_out;
output   Im_18_out_ap_vld;
output  [15:0] nextRe_34_out;
output   nextRe_34_out_ap_vld;
output  [15:0] Im_19_out;
output   Im_19_out_ap_vld;
output  [15:0] nextRe_35_out;
output   nextRe_35_out_ap_vld;
output  [15:0] Im_20_out;
output   Im_20_out_ap_vld;
output  [15:0] nextRe_36_out;
output   nextRe_36_out_ap_vld;
output  [15:0] Im_21_out;
output   Im_21_out_ap_vld;
output  [15:0] nextRe_37_out;
output   nextRe_37_out_ap_vld;
output  [15:0] Im_22_out;
output   Im_22_out_ap_vld;
output  [15:0] nextRe_38_out;
output   nextRe_38_out_ap_vld;
output  [15:0] Im_23_out;
output   Im_23_out_ap_vld;
output  [15:0] nextRe_39_out;
output   nextRe_39_out_ap_vld;
output  [15:0] Im_24_out;
output   Im_24_out_ap_vld;
output  [15:0] nextRe_40_out;
output   nextRe_40_out_ap_vld;
output  [15:0] Im_25_out;
output   Im_25_out_ap_vld;
output  [15:0] nextRe_41_out;
output   nextRe_41_out_ap_vld;
output  [15:0] Im_26_out;
output   Im_26_out_ap_vld;
output  [15:0] nextRe_42_out;
output   nextRe_42_out_ap_vld;
output  [15:0] Im_27_out;
output   Im_27_out_ap_vld;
output  [15:0] nextRe_43_out;
output   nextRe_43_out_ap_vld;
output  [15:0] Im_28_out;
output   Im_28_out_ap_vld;
output  [15:0] nextRe_44_out;
output   nextRe_44_out_ap_vld;
output  [15:0] Im_29_out;
output   Im_29_out_ap_vld;
output  [15:0] nextRe_45_out;
output   nextRe_45_out_ap_vld;
output  [15:0] Im_30_out;
output   Im_30_out_ap_vld;
output  [15:0] nextRe_46_out;
output   nextRe_46_out_ap_vld;
output  [15:0] Im_31_out;
output   Im_31_out_ap_vld;

reg ap_idle;
reg nextRe_out_ap_vld;
reg Im_16_out_ap_vld;
reg nextRe_32_out_ap_vld;
reg Im_17_out_ap_vld;
reg nextRe_33_out_ap_vld;
reg Im_18_out_ap_vld;
reg nextRe_34_out_ap_vld;
reg Im_19_out_ap_vld;
reg nextRe_35_out_ap_vld;
reg Im_20_out_ap_vld;
reg nextRe_36_out_ap_vld;
reg Im_21_out_ap_vld;
reg nextRe_37_out_ap_vld;
reg Im_22_out_ap_vld;
reg nextRe_38_out_ap_vld;
reg Im_23_out_ap_vld;
reg nextRe_39_out_ap_vld;
reg Im_24_out_ap_vld;
reg nextRe_40_out_ap_vld;
reg Im_25_out_ap_vld;
reg nextRe_41_out_ap_vld;
reg Im_26_out_ap_vld;
reg nextRe_42_out_ap_vld;
reg Im_27_out_ap_vld;
reg nextRe_43_out_ap_vld;
reg Im_28_out_ap_vld;
reg nextRe_44_out_ap_vld;
reg Im_29_out_ap_vld;
reg nextRe_45_out_ap_vld;
reg Im_30_out_ap_vld;
reg nextRe_46_out_ap_vld;
reg Im_31_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln157_reg_2991;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] TEMP1_address0;
wire   [0:0] TEMP1_q0;
wire   [5:0] HAB_address0;
wire   [15:0] HAB_q0;
wire   [5:0] T3R1_address0;
wire   [2:0] T3R1_q0;
wire   [2:0] MUX_A_IDX_address0;
wire   [3:0] MUX_A_IDX_q0;
wire   [5:0] T3R2_address0;
wire   [2:0] T3R2_q0;
wire   [2:0] MUX_B_IDX_address0;
wire   [3:0] MUX_B_IDX_q0;
wire   [5:0] T4R1_address0;
wire   [0:0] T4R1_q0;
wire   [5:0] T4R2_address0;
wire   [0:0] T4R2_q0;
wire   [5:0] ROM_ADDR_address0;
wire   [2:0] ROM_ADDR_q0;
wire   [2:0] TW_RE_address0;
wire   [15:0] TW_RE_q0;
wire   [2:0] TW_IM_address0;
wire   [14:0] TW_IM_q0;
wire   [5:0] T5R1_address0;
wire   [0:0] T5R1_q0;
wire   [5:0] T5R2_address0;
wire   [0:0] T5R2_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln157_fu_1155_p1;
reg   [63:0] zext_ln157_reg_2962;
wire   [0:0] icmp_ln157_fu_1169_p2;
reg   [0:0] icmp_ln157_reg_2991_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] T4R2_load_reg_3005;
reg   [3:0] MUX_A_IDX_load_reg_3021;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [3:0] MUX_B_IDX_load_reg_3027;
reg   [15:0] TW_RE_load_reg_3033;
reg  signed [14:0] TW_IM_load_reg_3038;
reg   [15:0] Im_152_load_reg_3044;
wire    ap_block_pp0_stage3_11001;
reg   [15:0] Im_144_load_reg_3049;
reg   [15:0] Im_136_load_reg_3054;
reg   [15:0] Im_128_load_reg_3059;
reg   [15:0] Im_1110_load_reg_3064;
reg   [15:0] Im_1012_load_reg_3069;
reg   [15:0] Im_914_load_reg_3074;
reg   [15:0] Im_816_load_reg_3079;
reg   [15:0] Im_718_load_reg_3084;
reg   [15:0] Im_620_load_reg_3089;
reg   [15:0] Im_522_load_reg_3094;
reg   [15:0] Im_424_load_reg_3099;
reg   [15:0] Im_326_load_reg_3104;
reg   [15:0] Im_228_load_reg_3109;
reg   [15:0] Im_130_load_reg_3114;
reg   [15:0] Im32_load_reg_3119;
reg   [15:0] Re_1534_load_reg_3124;
reg   [15:0] Re_1436_load_reg_3129;
reg   [15:0] Re_1338_load_reg_3134;
reg   [15:0] Re_1240_load_reg_3139;
reg   [15:0] Re_1142_load_reg_3144;
reg   [15:0] Re_1044_load_reg_3149;
reg   [15:0] Re_946_load_reg_3154;
reg   [15:0] Re_848_load_reg_3159;
reg   [15:0] Re_750_load_reg_3164;
reg   [15:0] Re_652_load_reg_3169;
reg   [15:0] Re_554_load_reg_3174;
reg   [15:0] Re_456_load_reg_3179;
reg   [15:0] Re_358_load_reg_3184;
reg   [15:0] Re_260_load_reg_3189;
reg   [15:0] Re_162_load_reg_3194;
reg   [15:0] Re64_load_reg_3199;
wire   [15:0] varR1_fu_1292_p31;
reg   [15:0] varR1_reg_3204;
wire   [15:0] varR2_fu_1355_p31;
reg   [15:0] varR2_reg_3209;
wire   [15:0] varI1_fu_1418_p31;
reg   [15:0] varI1_reg_3214;
wire   [15:0] varI2_fu_1481_p31;
reg   [15:0] varI2_reg_3219;
wire  signed [15:0] br_fu_1544_p3;
reg  signed [15:0] br_reg_3224;
wire  signed [15:0] bi_fu_1551_p3;
reg  signed [15:0] bi_reg_3230;
wire   [16:0] m2_fu_1562_p2;
reg  signed [16:0] m2_reg_3235;
wire   [30:0] m3_fu_1583_p2;
reg   [30:0] m3_reg_3255;
wire  signed [29:0] mul_ln122_fu_1592_p2;
reg  signed [29:0] mul_ln122_reg_3260;
wire   [28:0] trunc_ln122_fu_1598_p1;
reg   [28:0] trunc_ln122_reg_3265;
wire  signed [29:0] mul_ln126_fu_1605_p2;
reg  signed [29:0] mul_ln126_reg_3270;
wire   [28:0] trunc_ln126_fu_1611_p1;
reg   [28:0] trunc_ln126_reg_3275;
wire   [29:0] mul_ln127_fu_1615_p2;
reg   [29:0] mul_ln127_reg_3280;
reg   [0:0] TEMP1_load_reg_3295;
wire   [0:0] trunc_ln166_fu_1621_p1;
reg   [0:0] trunc_ln166_reg_3331;
wire   [15:0] ar_fu_1625_p3;
reg   [15:0] ar_reg_3337;
wire   [15:0] ai_fu_1631_p3;
reg   [15:0] ai_reg_3342;
wire  signed [15:0] trunca1_fu_1671_p3;
reg  signed [15:0] trunca1_reg_3347;
wire  signed [15:0] trunca2_fu_1705_p3;
reg  signed [15:0] trunca2_reg_3352;
wire   [15:0] trunca11_fu_1713_p2;
reg   [15:0] trunca11_reg_3357;
wire   [15:0] trunca21_fu_1719_p2;
reg   [15:0] trunca21_reg_3362;
reg   [0:0] T5R1_load_reg_3367;
reg   [0:0] T5R2_load_reg_3373;
reg   [0:0] tmp_6_reg_3379;
reg   [0:0] tmp_7_reg_3385;
reg   [0:0] tmp_8_reg_3391;
reg   [0:0] tmp_9_reg_3397;
reg   [0:0] tmp_10_reg_3403;
reg   [0:0] tmp_11_reg_3409;
reg   [0:0] tmp_12_reg_3415;
reg   [0:0] tmp_13_reg_3421;
reg   [0:0] tmp_14_reg_3427;
reg   [0:0] tmp_15_reg_3433;
reg   [0:0] tmp_16_reg_3439;
reg   [0:0] tmp_17_reg_3445;
reg   [0:0] tmp_18_reg_3451;
reg   [0:0] tmp_19_reg_3457;
reg   [0:0] tmp_20_reg_3463;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln166_fu_1180_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln167_fu_1185_p1;
wire   [63:0] zext_ln186_fu_1190_p1;
reg   [15:0] Im_152_fu_270;
wire   [15:0] Im_30_fu_2404_p3;
wire    ap_loop_init;
wire    ap_block_pp0_stage3;
reg   [15:0] Im_144_fu_274;
wire   [15:0] Im_29_fu_2378_p3;
reg   [15:0] Im_136_fu_278;
wire   [15:0] Im_28_fu_2352_p3;
reg   [15:0] Im_128_fu_282;
wire   [15:0] Im_27_fu_2326_p3;
reg   [15:0] Im_1110_fu_286;
wire   [15:0] Im_26_fu_2300_p3;
reg   [15:0] Im_1012_fu_290;
wire   [15:0] Im_25_fu_2274_p3;
reg   [15:0] Im_914_fu_294;
wire   [15:0] Im_24_fu_2248_p3;
reg   [15:0] Im_816_fu_298;
wire   [15:0] Im_23_fu_2222_p3;
reg   [15:0] Im_718_fu_302;
wire   [15:0] Im_22_fu_2196_p3;
reg   [15:0] Im_620_fu_306;
wire   [15:0] Im_21_fu_2170_p3;
reg   [15:0] Im_522_fu_310;
wire   [15:0] Im_20_fu_2144_p3;
reg   [15:0] Im_424_fu_314;
wire   [15:0] Im_19_fu_2118_p3;
reg   [15:0] Im_326_fu_318;
wire   [15:0] Im_18_fu_2092_p3;
reg   [15:0] Im_228_fu_322;
wire   [15:0] Im_17_fu_2066_p3;
reg   [15:0] Im_130_fu_326;
wire   [15:0] Im_16_fu_2040_p3;
reg   [15:0] Im32_fu_330;
wire   [15:0] Im_fu_2014_p3;
reg   [15:0] Re_1534_fu_334;
wire   [15:0] Re_30_fu_2397_p3;
reg   [15:0] Re_1436_fu_338;
wire   [15:0] Re_29_fu_2371_p3;
reg   [15:0] Re_1338_fu_342;
wire   [15:0] Re_28_fu_2345_p3;
reg   [15:0] Re_1240_fu_346;
wire   [15:0] Re_27_fu_2319_p3;
reg   [15:0] Re_1142_fu_350;
wire   [15:0] Re_26_fu_2293_p3;
reg   [15:0] Re_1044_fu_354;
wire   [15:0] Re_25_fu_2267_p3;
reg   [15:0] Re_946_fu_358;
wire   [15:0] Re_24_fu_2241_p3;
reg   [15:0] Re_848_fu_362;
wire   [15:0] Re_23_fu_2215_p3;
reg   [15:0] Re_750_fu_366;
wire   [15:0] Re_22_fu_2189_p3;
reg   [15:0] Re_652_fu_370;
wire   [15:0] Re_21_fu_2163_p3;
reg   [15:0] Re_554_fu_374;
wire   [15:0] Re_20_fu_2137_p3;
reg   [15:0] Re_456_fu_378;
wire   [15:0] Re_19_fu_2111_p3;
reg   [15:0] Re_358_fu_382;
wire   [15:0] Re_18_fu_2085_p3;
reg   [15:0] Re_260_fu_386;
wire   [15:0] Re_17_fu_2059_p3;
reg   [15:0] Re_162_fu_390;
wire   [15:0] Re_16_fu_2033_p3;
reg   [15:0] Re64_fu_394;
wire   [15:0] Re_fu_2007_p3;
reg   [5:0] st65_fu_398;
wire   [5:0] st_fu_1163_p2;
reg   [5:0] ap_sig_allocacmp_st65_load;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage2;
reg    ap_idle_pp0_0to0;
wire    ap_block_pp0_stage2_01001;
reg    T3R1_ce0_local;
reg    T3R2_ce0_local;
reg    T4R2_ce0_local;
reg    ROM_ADDR_ce0_local;
reg    MUX_A_IDX_ce0_local;
reg    MUX_B_IDX_ce0_local;
reg    TW_RE_ce0_local;
reg    TW_IM_ce0_local;
reg    TEMP1_ce0_local;
reg    HAB_ce0_local;
reg    T4R1_ce0_local;
reg    T5R1_ce0_local;
reg    T5R2_ce0_local;
wire   [15:0] varR1_fu_1292_p29;
wire   [15:0] varR2_fu_1355_p29;
wire   [15:0] varI1_fu_1418_p29;
wire   [15:0] varI2_fu_1481_p29;
wire  signed [16:0] sext_ln122_fu_1558_p1;
wire  signed [15:0] mul_ln122_fu_1592_p0;
wire  signed [29:0] sext_ln121_1_fu_1571_p1;
wire  signed [15:0] mul_ln127_fu_1615_p0;
wire  signed [30:0] sext_ln126_2_fu_1640_p1;
wire  signed [30:0] sext_ln122_2_fu_1637_p1;
wire   [28:0] add_ln126_fu_1643_p2;
wire   [30:0] add_ln126_1_fu_1647_p2;
wire   [0:0] tmp_fu_1663_p3;
wire   [14:0] trunc_ln1_fu_1653_p4;
wire  signed [30:0] sext_ln127_fu_1679_p1;
wire   [30:0] add_ln127_fu_1682_p2;
wire   [0:0] tmp_1_fu_1697_p3;
wire   [14:0] trunc_ln102_1_fu_1687_p4;
wire    ap_block_pp0_stage2;
wire  signed [16:0] sext_ln110_1_fu_1848_p1;
wire  signed [16:0] sext_ln110_fu_1845_p1;
wire   [16:0] sum_fu_1851_p2;
wire   [0:0] tmp_2_fu_1861_p3;
wire   [14:0] trunc_ln87_fu_1857_p1;
wire  signed [16:0] sext_ln110_2_fu_1877_p1;
wire   [16:0] sum_1_fu_1880_p2;
wire   [0:0] tmp_3_fu_1890_p3;
wire   [14:0] trunc_ln87_1_fu_1886_p1;
wire  signed [16:0] sext_ln110_4_fu_1909_p1;
wire  signed [16:0] sext_ln110_3_fu_1906_p1;
wire   [16:0] sum_2_fu_1912_p2;
wire   [0:0] tmp_4_fu_1922_p3;
wire   [14:0] trunc_ln87_2_fu_1918_p1;
wire  signed [16:0] sext_ln110_5_fu_1938_p1;
wire   [16:0] sum_3_fu_1941_p2;
wire   [0:0] tmp_5_fu_1951_p3;
wire   [14:0] trunc_ln87_3_fu_1947_p1;
wire   [15:0] dr_fu_1898_p3;
wire   [15:0] cr_fu_1869_p3;
wire   [15:0] di_fu_1959_p3;
wire   [15:0] ci_fu_1930_p3;
wire   [15:0] p0r_fu_1967_p3;
wire   [15:0] p0i_fu_1981_p3;
wire   [15:0] srcR_31_fu_1995_p3;
wire   [15:0] srcI_fu_2001_p3;
wire   [15:0] p1r_fu_1974_p3;
wire   [15:0] p1i_fu_1988_p3;
wire   [15:0] srcR_32_fu_2021_p3;
wire   [15:0] srcI_2_fu_2027_p3;
wire   [15:0] srcR_33_fu_2047_p3;
wire   [15:0] srcI_4_fu_2053_p3;
wire   [15:0] srcR_34_fu_2073_p3;
wire   [15:0] srcI_6_fu_2079_p3;
wire   [15:0] srcR_35_fu_2099_p3;
wire   [15:0] srcI_8_fu_2105_p3;
wire   [15:0] srcR_36_fu_2125_p3;
wire   [15:0] srcI_10_fu_2131_p3;
wire   [15:0] srcR_37_fu_2151_p3;
wire   [15:0] srcI_12_fu_2157_p3;
wire   [15:0] srcR_38_fu_2177_p3;
wire   [15:0] srcI_14_fu_2183_p3;
wire   [15:0] srcR_39_fu_2203_p3;
wire   [15:0] srcI_16_fu_2209_p3;
wire   [15:0] srcR_40_fu_2229_p3;
wire   [15:0] srcI_18_fu_2235_p3;
wire   [15:0] srcR_41_fu_2255_p3;
wire   [15:0] srcI_20_fu_2261_p3;
wire   [15:0] srcR_42_fu_2281_p3;
wire   [15:0] srcI_22_fu_2287_p3;
wire   [15:0] srcR_43_fu_2307_p3;
wire   [15:0] srcI_24_fu_2313_p3;
wire   [15:0] srcR_44_fu_2333_p3;
wire   [15:0] srcI_26_fu_2339_p3;
wire   [15:0] srcR_45_fu_2359_p3;
wire   [15:0] srcI_28_fu_2365_p3;
wire   [15:0] srcR_46_fu_2385_p3;
wire   [15:0] srcI_30_fu_2391_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] varR1_fu_1292_p1;
wire   [3:0] varR1_fu_1292_p3;
wire   [3:0] varR1_fu_1292_p5;
wire   [3:0] varR1_fu_1292_p7;
wire   [3:0] varR1_fu_1292_p9;
wire   [3:0] varR1_fu_1292_p11;
wire   [3:0] varR1_fu_1292_p13;
wire  signed [3:0] varR1_fu_1292_p15;
wire  signed [3:0] varR1_fu_1292_p17;
wire  signed [3:0] varR1_fu_1292_p19;
wire  signed [3:0] varR1_fu_1292_p21;
wire  signed [3:0] varR1_fu_1292_p23;
wire  signed [3:0] varR1_fu_1292_p25;
wire  signed [3:0] varR1_fu_1292_p27;
wire   [3:0] varR2_fu_1355_p1;
wire   [3:0] varR2_fu_1355_p3;
wire   [3:0] varR2_fu_1355_p5;
wire   [3:0] varR2_fu_1355_p7;
wire   [3:0] varR2_fu_1355_p9;
wire   [3:0] varR2_fu_1355_p11;
wire   [3:0] varR2_fu_1355_p13;
wire  signed [3:0] varR2_fu_1355_p15;
wire  signed [3:0] varR2_fu_1355_p17;
wire  signed [3:0] varR2_fu_1355_p19;
wire  signed [3:0] varR2_fu_1355_p21;
wire  signed [3:0] varR2_fu_1355_p23;
wire  signed [3:0] varR2_fu_1355_p25;
wire  signed [3:0] varR2_fu_1355_p27;
wire   [3:0] varI1_fu_1418_p1;
wire   [3:0] varI1_fu_1418_p3;
wire   [3:0] varI1_fu_1418_p5;
wire   [3:0] varI1_fu_1418_p7;
wire   [3:0] varI1_fu_1418_p9;
wire   [3:0] varI1_fu_1418_p11;
wire   [3:0] varI1_fu_1418_p13;
wire  signed [3:0] varI1_fu_1418_p15;
wire  signed [3:0] varI1_fu_1418_p17;
wire  signed [3:0] varI1_fu_1418_p19;
wire  signed [3:0] varI1_fu_1418_p21;
wire  signed [3:0] varI1_fu_1418_p23;
wire  signed [3:0] varI1_fu_1418_p25;
wire  signed [3:0] varI1_fu_1418_p27;
wire   [3:0] varI2_fu_1481_p1;
wire   [3:0] varI2_fu_1481_p3;
wire   [3:0] varI2_fu_1481_p5;
wire   [3:0] varI2_fu_1481_p7;
wire   [3:0] varI2_fu_1481_p9;
wire   [3:0] varI2_fu_1481_p11;
wire   [3:0] varI2_fu_1481_p13;
wire  signed [3:0] varI2_fu_1481_p15;
wire  signed [3:0] varI2_fu_1481_p17;
wire  signed [3:0] varI2_fu_1481_p19;
wire  signed [3:0] varI2_fu_1481_p21;
wire  signed [3:0] varI2_fu_1481_p23;
wire  signed [3:0] varI2_fu_1481_p25;
wire  signed [3:0] varI2_fu_1481_p27;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 Im_152_fu_270 = 16'd0;
#0 Im_144_fu_274 = 16'd0;
#0 Im_136_fu_278 = 16'd0;
#0 Im_128_fu_282 = 16'd0;
#0 Im_1110_fu_286 = 16'd0;
#0 Im_1012_fu_290 = 16'd0;
#0 Im_914_fu_294 = 16'd0;
#0 Im_816_fu_298 = 16'd0;
#0 Im_718_fu_302 = 16'd0;
#0 Im_620_fu_306 = 16'd0;
#0 Im_522_fu_310 = 16'd0;
#0 Im_424_fu_314 = 16'd0;
#0 Im_326_fu_318 = 16'd0;
#0 Im_228_fu_322 = 16'd0;
#0 Im_130_fu_326 = 16'd0;
#0 Im32_fu_330 = 16'd0;
#0 Re_1534_fu_334 = 16'd0;
#0 Re_1436_fu_338 = 16'd0;
#0 Re_1338_fu_342 = 16'd0;
#0 Re_1240_fu_346 = 16'd0;
#0 Re_1142_fu_350 = 16'd0;
#0 Re_1044_fu_354 = 16'd0;
#0 Re_946_fu_358 = 16'd0;
#0 Re_848_fu_362 = 16'd0;
#0 Re_750_fu_366 = 16'd0;
#0 Re_652_fu_370 = 16'd0;
#0 Re_554_fu_374 = 16'd0;
#0 Re_456_fu_378 = 16'd0;
#0 Re_358_fu_382 = 16'd0;
#0 Re_260_fu_386 = 16'd0;
#0 Re_162_fu_390 = 16'd0;
#0 Re64_fu_394 = 16'd0;
#0 st65_fu_398 = 6'd0;
#0 ap_done_reg = 1'b0;
end

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_TEMP1_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
TEMP1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TEMP1_address0),
    .ce0(TEMP1_ce0_local),
    .q0(TEMP1_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_HAB_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
HAB_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(HAB_address0),
    .ce0(HAB_ce0_local),
    .q0(HAB_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T3R1_ROM_AUTO_1R #(
    .DataWidth( 3 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
T3R1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(T3R1_address0),
    .ce0(T3R1_ce0_local),
    .q0(T3R1_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_MUX_A_IDX_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
MUX_A_IDX_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(MUX_A_IDX_address0),
    .ce0(MUX_A_IDX_ce0_local),
    .q0(MUX_A_IDX_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T3R2_ROM_AUTO_1R #(
    .DataWidth( 3 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
T3R2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(T3R2_address0),
    .ce0(T3R2_ce0_local),
    .q0(T3R2_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_MUX_B_IDX_ROM_AUTO_1R #(
    .DataWidth( 4 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
MUX_B_IDX_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(MUX_B_IDX_address0),
    .ce0(MUX_B_IDX_ce0_local),
    .q0(MUX_B_IDX_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T4R1_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
T4R1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(T4R1_address0),
    .ce0(T4R1_ce0_local),
    .q0(T4R1_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T4R2_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
T4R2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(T4R2_address0),
    .ce0(T4R2_ce0_local),
    .q0(T4R2_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_ROM_ADDR_ROM_AUTO_1R #(
    .DataWidth( 3 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
ROM_ADDR_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ROM_ADDR_address0),
    .ce0(ROM_ADDR_ce0_local),
    .q0(ROM_ADDR_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_TW_RE_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TW_RE_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TW_RE_address0),
    .ce0(TW_RE_ce0_local),
    .q0(TW_RE_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_TW_IM_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TW_IM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TW_IM_address0),
    .ce0(TW_IM_ce0_local),
    .q0(TW_IM_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T4R1_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
T5R1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(T5R1_address0),
    .ce0(T5R1_ce0_local),
    .q0(T5R1_q0)
);

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T4R2_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
T5R2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(T5R2_address0),
    .ce0(T5R2_ce0_local),
    .q0(T5R2_q0)
);

(* dissolve_hierarchy = "yes" *) fft16_hls_sparsemux_29_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h9 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'hA ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'hB ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'hC ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hD ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hE ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hF ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_29_4_16_1_1_U1(
    .din0(Re64_fu_394),
    .din1(Re_162_fu_390),
    .din2(Re_260_fu_386),
    .din3(Re_358_fu_382),
    .din4(Re_456_fu_378),
    .din5(Re_554_fu_374),
    .din6(Re_652_fu_370),
    .din7(Re_946_fu_358),
    .din8(Re_1044_fu_354),
    .din9(Re_1142_fu_350),
    .din10(Re_1240_fu_346),
    .din11(Re_1338_fu_342),
    .din12(Re_1436_fu_338),
    .din13(Re_1534_fu_334),
    .def(varR1_fu_1292_p29),
    .sel(MUX_A_IDX_load_reg_3021),
    .dout(varR1_fu_1292_p31)
);

(* dissolve_hierarchy = "yes" *) fft16_hls_sparsemux_29_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h4 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h5 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h6 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h7 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h8 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h9 ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'hA ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'hB ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hC ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hD ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hE ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_29_4_16_1_1_U2(
    .din0(Re_162_fu_390),
    .din1(Re_260_fu_386),
    .din2(Re_358_fu_382),
    .din3(Re_456_fu_378),
    .din4(Re_554_fu_374),
    .din5(Re_652_fu_370),
    .din6(Re_750_fu_366),
    .din7(Re_848_fu_362),
    .din8(Re_946_fu_358),
    .din9(Re_1044_fu_354),
    .din10(Re_1142_fu_350),
    .din11(Re_1240_fu_346),
    .din12(Re_1338_fu_342),
    .din13(Re_1436_fu_338),
    .def(varR2_fu_1355_p29),
    .sel(MUX_B_IDX_load_reg_3027),
    .dout(varR2_fu_1355_p31)
);

(* dissolve_hierarchy = "yes" *) fft16_hls_sparsemux_29_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h9 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'hA ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'hB ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'hC ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hD ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hE ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hF ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_29_4_16_1_1_U3(
    .din0(Im32_fu_330),
    .din1(Im_130_fu_326),
    .din2(Im_228_fu_322),
    .din3(Im_326_fu_318),
    .din4(Im_424_fu_314),
    .din5(Im_522_fu_310),
    .din6(Im_620_fu_306),
    .din7(Im_914_fu_294),
    .din8(Im_1012_fu_290),
    .din9(Im_1110_fu_286),
    .din10(Im_128_fu_282),
    .din11(Im_136_fu_278),
    .din12(Im_144_fu_274),
    .din13(Im_152_fu_270),
    .def(varI1_fu_1418_p29),
    .sel(MUX_A_IDX_load_reg_3021),
    .dout(varI1_fu_1418_p31)
);

(* dissolve_hierarchy = "yes" *) fft16_hls_sparsemux_29_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h4 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h5 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h6 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h7 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h8 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h9 ),
    .din8_WIDTH( 16 ),
    .CASE9( 4'hA ),
    .din9_WIDTH( 16 ),
    .CASE10( 4'hB ),
    .din10_WIDTH( 16 ),
    .CASE11( 4'hC ),
    .din11_WIDTH( 16 ),
    .CASE12( 4'hD ),
    .din12_WIDTH( 16 ),
    .CASE13( 4'hE ),
    .din13_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_29_4_16_1_1_U4(
    .din0(Im_130_fu_326),
    .din1(Im_228_fu_322),
    .din2(Im_326_fu_318),
    .din3(Im_424_fu_314),
    .din4(Im_522_fu_310),
    .din5(Im_620_fu_306),
    .din6(Im_718_fu_302),
    .din7(Im_816_fu_298),
    .din8(Im_914_fu_294),
    .din9(Im_1012_fu_290),
    .din10(Im_1110_fu_286),
    .din11(Im_128_fu_282),
    .din12(Im_136_fu_278),
    .din13(Im_144_fu_274),
    .def(varI2_fu_1481_p29),
    .sel(MUX_B_IDX_load_reg_3027),
    .dout(varI2_fu_1481_p31)
);

fft16_hls_mul_15s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_15s_16s_31_1_1_U5(
    .din0(TW_IM_load_reg_3038),
    .din1(br_reg_3224),
    .dout(m3_fu_1583_p2)
);

fft16_hls_mul_16s_16s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
mul_16s_16s_30_1_1_U6(
    .din0(mul_ln122_fu_1592_p0),
    .din1(br_reg_3224),
    .dout(mul_ln122_fu_1592_p2)
);

fft16_hls_mul_15s_17s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 30 ))
mul_15s_17s_30_1_1_U7(
    .din0(TW_IM_load_reg_3038),
    .din1(m2_reg_3235),
    .dout(mul_ln126_fu_1605_p2)
);

fft16_hls_mul_16s_16s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
mul_16s_16s_30_1_1_U8(
    .din0(mul_ln127_fu_1615_p0),
    .din1(bi_reg_3230),
    .dout(mul_ln127_fu_1615_p2)
);

fft16_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im32_fu_330 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im32_fu_330 <= Im_fu_2014_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_1012_fu_290 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_1012_fu_290 <= Im_25_fu_2274_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_1110_fu_286 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_1110_fu_286 <= Im_26_fu_2300_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_128_fu_282 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_128_fu_282 <= Im_27_fu_2326_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_130_fu_326 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_130_fu_326 <= Im_16_fu_2040_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_136_fu_278 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_136_fu_278 <= Im_28_fu_2352_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_144_fu_274 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_144_fu_274 <= Im_29_fu_2378_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_152_fu_270 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_152_fu_270 <= Im_30_fu_2404_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_228_fu_322 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_228_fu_322 <= Im_17_fu_2066_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_326_fu_318 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_326_fu_318 <= Im_18_fu_2092_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_424_fu_314 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_424_fu_314 <= Im_19_fu_2118_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_522_fu_310 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_522_fu_310 <= Im_20_fu_2144_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_620_fu_306 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_620_fu_306 <= Im_21_fu_2170_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_718_fu_302 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_718_fu_302 <= Im_22_fu_2196_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_816_fu_298 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_816_fu_298 <= Im_23_fu_2222_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Im_914_fu_294 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_914_fu_294 <= Im_24_fu_2248_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re64_fu_394 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re64_fu_394 <= Re_fu_2007_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_1044_fu_354 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_1044_fu_354 <= Re_25_fu_2267_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_1142_fu_350 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_1142_fu_350 <= Re_26_fu_2293_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_1240_fu_346 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_1240_fu_346 <= Re_27_fu_2319_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_1338_fu_342 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_1338_fu_342 <= Re_28_fu_2345_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_1436_fu_338 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_1436_fu_338 <= Re_29_fu_2371_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_1534_fu_334 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_1534_fu_334 <= Re_30_fu_2397_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_162_fu_390 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_162_fu_390 <= Re_16_fu_2033_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_260_fu_386 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_260_fu_386 <= Re_17_fu_2059_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_358_fu_382 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_358_fu_382 <= Re_18_fu_2085_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_456_fu_378 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_456_fu_378 <= Re_19_fu_2111_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_554_fu_374 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_554_fu_374 <= Re_20_fu_2137_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_652_fu_370 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_652_fu_370 <= Re_21_fu_2163_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_750_fu_366 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_750_fu_366 <= Re_22_fu_2189_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_848_fu_362 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_848_fu_362 <= Re_23_fu_2215_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Re_946_fu_358 <= 16'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Re_946_fu_358 <= Re_24_fu_2241_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage2)))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            st65_fu_398 <= st_fu_1163_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            st65_fu_398 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        Im32_load_reg_3119 <= Im32_fu_330;
        Im_1012_load_reg_3069 <= Im_1012_fu_290;
        Im_1110_load_reg_3064 <= Im_1110_fu_286;
        Im_128_load_reg_3059 <= Im_128_fu_282;
        Im_130_load_reg_3114 <= Im_130_fu_326;
        Im_136_load_reg_3054 <= Im_136_fu_278;
        Im_144_load_reg_3049 <= Im_144_fu_274;
        Im_152_load_reg_3044 <= Im_152_fu_270;
        Im_228_load_reg_3109 <= Im_228_fu_322;
        Im_326_load_reg_3104 <= Im_326_fu_318;
        Im_424_load_reg_3099 <= Im_424_fu_314;
        Im_522_load_reg_3094 <= Im_522_fu_310;
        Im_620_load_reg_3089 <= Im_620_fu_306;
        Im_718_load_reg_3084 <= Im_718_fu_302;
        Im_816_load_reg_3079 <= Im_816_fu_298;
        Im_914_load_reg_3074 <= Im_914_fu_294;
        Re64_load_reg_3199 <= Re64_fu_394;
        Re_1044_load_reg_3149 <= Re_1044_fu_354;
        Re_1142_load_reg_3144 <= Re_1142_fu_350;
        Re_1240_load_reg_3139 <= Re_1240_fu_346;
        Re_1338_load_reg_3134 <= Re_1338_fu_342;
        Re_1436_load_reg_3129 <= Re_1436_fu_338;
        Re_1534_load_reg_3124 <= Re_1534_fu_334;
        Re_162_load_reg_3194 <= Re_162_fu_390;
        Re_260_load_reg_3189 <= Re_260_fu_386;
        Re_358_load_reg_3184 <= Re_358_fu_382;
        Re_456_load_reg_3179 <= Re_456_fu_378;
        Re_554_load_reg_3174 <= Re_554_fu_374;
        Re_652_load_reg_3169 <= Re_652_fu_370;
        Re_750_load_reg_3164 <= Re_750_fu_366;
        Re_848_load_reg_3159 <= Re_848_fu_362;
        Re_946_load_reg_3154 <= Re_946_fu_358;
        bi_reg_3230 <= bi_fu_1551_p3;
        br_reg_3224 <= br_fu_1544_p3;
        m2_reg_3235 <= m2_fu_1562_p2;
        varI1_reg_3214 <= varI1_fu_1418_p31;
        varI2_reg_3219 <= varI2_fu_1481_p31;
        varR1_reg_3204 <= varR1_fu_1292_p31;
        varR2_reg_3209 <= varR2_fu_1355_p31;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        MUX_A_IDX_load_reg_3021 <= MUX_A_IDX_q0;
        MUX_B_IDX_load_reg_3027 <= MUX_B_IDX_q0;
        TW_IM_load_reg_3038 <= TW_IM_q0;
        TW_RE_load_reg_3033 <= TW_RE_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        T4R2_load_reg_3005 <= T4R2_q0;
        T5R1_load_reg_3367 <= T5R1_q0;
        T5R2_load_reg_3373 <= T5R2_q0;
        TEMP1_load_reg_3295 <= TEMP1_q0;
        ai_reg_3342 <= ai_fu_1631_p3;
        ar_reg_3337 <= ar_fu_1625_p3;
        tmp_10_reg_3403 <= HAB_q0[32'd5];
        tmp_11_reg_3409 <= HAB_q0[32'd6];
        tmp_12_reg_3415 <= HAB_q0[32'd7];
        tmp_13_reg_3421 <= HAB_q0[32'd8];
        tmp_14_reg_3427 <= HAB_q0[32'd9];
        tmp_15_reg_3433 <= HAB_q0[32'd10];
        tmp_16_reg_3439 <= HAB_q0[32'd11];
        tmp_17_reg_3445 <= HAB_q0[32'd12];
        tmp_18_reg_3451 <= HAB_q0[32'd13];
        tmp_19_reg_3457 <= HAB_q0[32'd14];
        tmp_20_reg_3463 <= HAB_q0[32'd15];
        tmp_6_reg_3379 <= HAB_q0[32'd1];
        tmp_7_reg_3385 <= HAB_q0[32'd2];
        tmp_8_reg_3391 <= HAB_q0[32'd3];
        tmp_9_reg_3397 <= HAB_q0[32'd4];
        trunc_ln166_reg_3331 <= trunc_ln166_fu_1621_p1;
        trunca11_reg_3357 <= trunca11_fu_1713_p2;
        trunca1_reg_3347 <= trunca1_fu_1671_p3;
        trunca21_reg_3362 <= trunca21_fu_1719_p2;
        trunca2_reg_3352 <= trunca2_fu_1705_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln157_reg_2991 <= icmp_ln157_fu_1169_p2;
        icmp_ln157_reg_2991_pp0_iter1_reg <= icmp_ln157_reg_2991;
        m3_reg_3255 <= m3_fu_1583_p2;
        mul_ln122_reg_3260 <= mul_ln122_fu_1592_p2;
        mul_ln126_reg_3270 <= mul_ln126_fu_1605_p2;
        mul_ln127_reg_3280 <= mul_ln127_fu_1615_p2;
        trunc_ln122_reg_3265 <= trunc_ln122_fu_1598_p1;
        trunc_ln126_reg_3275 <= trunc_ln126_fu_1611_p1;
        zext_ln157_reg_2962[5 : 0] <= zext_ln157_fu_1155_p1[5 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        HAB_ce0_local = 1'b1;
    end else begin
        HAB_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_16_out_ap_vld = 1'b1;
    end else begin
        Im_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_17_out_ap_vld = 1'b1;
    end else begin
        Im_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_18_out_ap_vld = 1'b1;
    end else begin
        Im_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_19_out_ap_vld = 1'b1;
    end else begin
        Im_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_20_out_ap_vld = 1'b1;
    end else begin
        Im_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_21_out_ap_vld = 1'b1;
    end else begin
        Im_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_22_out_ap_vld = 1'b1;
    end else begin
        Im_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_23_out_ap_vld = 1'b1;
    end else begin
        Im_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_24_out_ap_vld = 1'b1;
    end else begin
        Im_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_25_out_ap_vld = 1'b1;
    end else begin
        Im_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_26_out_ap_vld = 1'b1;
    end else begin
        Im_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_27_out_ap_vld = 1'b1;
    end else begin
        Im_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_28_out_ap_vld = 1'b1;
    end else begin
        Im_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_29_out_ap_vld = 1'b1;
    end else begin
        Im_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_30_out_ap_vld = 1'b1;
    end else begin
        Im_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Im_31_out_ap_vld = 1'b1;
    end else begin
        Im_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        MUX_A_IDX_ce0_local = 1'b1;
    end else begin
        MUX_A_IDX_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        MUX_B_IDX_ce0_local = 1'b1;
    end else begin
        MUX_B_IDX_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ROM_ADDR_ce0_local = 1'b1;
    end else begin
        ROM_ADDR_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        T3R1_ce0_local = 1'b1;
    end else begin
        T3R1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        T3R2_ce0_local = 1'b1;
    end else begin
        T3R2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        T4R1_ce0_local = 1'b1;
    end else begin
        T4R1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        T4R2_ce0_local = 1'b1;
    end else begin
        T4R2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        T5R1_ce0_local = 1'b1;
    end else begin
        T5R1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        T5R2_ce0_local = 1'b1;
    end else begin
        T5R2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TEMP1_ce0_local = 1'b1;
    end else begin
        TEMP1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        TW_IM_ce0_local = 1'b1;
    end else begin
        TW_IM_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        TW_RE_ce0_local = 1'b1;
    end else begin
        TW_RE_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln157_reg_2991 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter1_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_st65_load = 6'd0;
    end else begin
        ap_sig_allocacmp_st65_load = st65_fu_398;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_32_out_ap_vld = 1'b1;
    end else begin
        nextRe_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_33_out_ap_vld = 1'b1;
    end else begin
        nextRe_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_34_out_ap_vld = 1'b1;
    end else begin
        nextRe_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_35_out_ap_vld = 1'b1;
    end else begin
        nextRe_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_36_out_ap_vld = 1'b1;
    end else begin
        nextRe_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_37_out_ap_vld = 1'b1;
    end else begin
        nextRe_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_38_out_ap_vld = 1'b1;
    end else begin
        nextRe_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_39_out_ap_vld = 1'b1;
    end else begin
        nextRe_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_40_out_ap_vld = 1'b1;
    end else begin
        nextRe_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_41_out_ap_vld = 1'b1;
    end else begin
        nextRe_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_42_out_ap_vld = 1'b1;
    end else begin
        nextRe_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_43_out_ap_vld = 1'b1;
    end else begin
        nextRe_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_44_out_ap_vld = 1'b1;
    end else begin
        nextRe_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_45_out_ap_vld = 1'b1;
    end else begin
        nextRe_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_46_out_ap_vld = 1'b1;
    end else begin
        nextRe_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln157_reg_2991_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        nextRe_out_ap_vld = 1'b1;
    end else begin
        nextRe_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HAB_address0 = zext_ln157_reg_2962;

assign Im_16_fu_2040_p3 = ((tmp_6_reg_3379[0:0] == 1'b1) ? srcI_2_fu_2027_p3 : Im_130_load_reg_3114);

assign Im_16_out = ((trunc_ln166_reg_3331[0:0] == 1'b1) ? srcI_fu_2001_p3 : Im32_load_reg_3119);

assign Im_17_fu_2066_p3 = ((tmp_7_reg_3385[0:0] == 1'b1) ? srcI_4_fu_2053_p3 : Im_228_load_reg_3109);

assign Im_17_out = ((tmp_6_reg_3379[0:0] == 1'b1) ? srcI_2_fu_2027_p3 : Im_130_load_reg_3114);

assign Im_18_fu_2092_p3 = ((tmp_8_reg_3391[0:0] == 1'b1) ? srcI_6_fu_2079_p3 : Im_326_load_reg_3104);

assign Im_18_out = ((tmp_7_reg_3385[0:0] == 1'b1) ? srcI_4_fu_2053_p3 : Im_228_load_reg_3109);

assign Im_19_fu_2118_p3 = ((tmp_9_reg_3397[0:0] == 1'b1) ? srcI_8_fu_2105_p3 : Im_424_load_reg_3099);

assign Im_19_out = ((tmp_8_reg_3391[0:0] == 1'b1) ? srcI_6_fu_2079_p3 : Im_326_load_reg_3104);

assign Im_20_fu_2144_p3 = ((tmp_10_reg_3403[0:0] == 1'b1) ? srcI_10_fu_2131_p3 : Im_522_load_reg_3094);

assign Im_20_out = ((tmp_9_reg_3397[0:0] == 1'b1) ? srcI_8_fu_2105_p3 : Im_424_load_reg_3099);

assign Im_21_fu_2170_p3 = ((tmp_11_reg_3409[0:0] == 1'b1) ? srcI_12_fu_2157_p3 : Im_620_load_reg_3089);

assign Im_21_out = ((tmp_10_reg_3403[0:0] == 1'b1) ? srcI_10_fu_2131_p3 : Im_522_load_reg_3094);

assign Im_22_fu_2196_p3 = ((tmp_12_reg_3415[0:0] == 1'b1) ? srcI_14_fu_2183_p3 : Im_718_load_reg_3084);

assign Im_22_out = ((tmp_11_reg_3409[0:0] == 1'b1) ? srcI_12_fu_2157_p3 : Im_620_load_reg_3089);

assign Im_23_fu_2222_p3 = ((tmp_13_reg_3421[0:0] == 1'b1) ? srcI_16_fu_2209_p3 : Im_816_load_reg_3079);

assign Im_23_out = ((tmp_12_reg_3415[0:0] == 1'b1) ? srcI_14_fu_2183_p3 : Im_718_load_reg_3084);

assign Im_24_fu_2248_p3 = ((tmp_14_reg_3427[0:0] == 1'b1) ? srcI_18_fu_2235_p3 : Im_914_load_reg_3074);

assign Im_24_out = ((tmp_13_reg_3421[0:0] == 1'b1) ? srcI_16_fu_2209_p3 : Im_816_load_reg_3079);

assign Im_25_fu_2274_p3 = ((tmp_15_reg_3433[0:0] == 1'b1) ? srcI_20_fu_2261_p3 : Im_1012_load_reg_3069);

assign Im_25_out = ((tmp_14_reg_3427[0:0] == 1'b1) ? srcI_18_fu_2235_p3 : Im_914_load_reg_3074);

assign Im_26_fu_2300_p3 = ((tmp_16_reg_3439[0:0] == 1'b1) ? srcI_22_fu_2287_p3 : Im_1110_load_reg_3064);

assign Im_26_out = ((tmp_15_reg_3433[0:0] == 1'b1) ? srcI_20_fu_2261_p3 : Im_1012_load_reg_3069);

assign Im_27_fu_2326_p3 = ((tmp_17_reg_3445[0:0] == 1'b1) ? srcI_24_fu_2313_p3 : Im_128_load_reg_3059);

assign Im_27_out = ((tmp_16_reg_3439[0:0] == 1'b1) ? srcI_22_fu_2287_p3 : Im_1110_load_reg_3064);

assign Im_28_fu_2352_p3 = ((tmp_18_reg_3451[0:0] == 1'b1) ? srcI_26_fu_2339_p3 : Im_136_load_reg_3054);

assign Im_28_out = ((tmp_17_reg_3445[0:0] == 1'b1) ? srcI_24_fu_2313_p3 : Im_128_load_reg_3059);

assign Im_29_fu_2378_p3 = ((tmp_19_reg_3457[0:0] == 1'b1) ? srcI_28_fu_2365_p3 : Im_144_load_reg_3049);

assign Im_29_out = ((tmp_18_reg_3451[0:0] == 1'b1) ? srcI_26_fu_2339_p3 : Im_136_load_reg_3054);

assign Im_30_fu_2404_p3 = ((tmp_20_reg_3463[0:0] == 1'b1) ? srcI_30_fu_2391_p3 : Im_152_load_reg_3044);

assign Im_30_out = ((tmp_19_reg_3457[0:0] == 1'b1) ? srcI_28_fu_2365_p3 : Im_144_load_reg_3049);

assign Im_31_out = ((tmp_20_reg_3463[0:0] == 1'b1) ? srcI_30_fu_2391_p3 : Im_152_load_reg_3044);

assign Im_fu_2014_p3 = ((trunc_ln166_reg_3331[0:0] == 1'b1) ? srcI_fu_2001_p3 : Im32_load_reg_3119);

assign MUX_A_IDX_address0 = zext_ln166_fu_1180_p1;

assign MUX_B_IDX_address0 = zext_ln167_fu_1185_p1;

assign ROM_ADDR_address0 = zext_ln157_fu_1155_p1;

assign Re_16_fu_2033_p3 = ((tmp_6_reg_3379[0:0] == 1'b1) ? srcR_32_fu_2021_p3 : Re_162_load_reg_3194);

assign Re_17_fu_2059_p3 = ((tmp_7_reg_3385[0:0] == 1'b1) ? srcR_33_fu_2047_p3 : Re_260_load_reg_3189);

assign Re_18_fu_2085_p3 = ((tmp_8_reg_3391[0:0] == 1'b1) ? srcR_34_fu_2073_p3 : Re_358_load_reg_3184);

assign Re_19_fu_2111_p3 = ((tmp_9_reg_3397[0:0] == 1'b1) ? srcR_35_fu_2099_p3 : Re_456_load_reg_3179);

assign Re_20_fu_2137_p3 = ((tmp_10_reg_3403[0:0] == 1'b1) ? srcR_36_fu_2125_p3 : Re_554_load_reg_3174);

assign Re_21_fu_2163_p3 = ((tmp_11_reg_3409[0:0] == 1'b1) ? srcR_37_fu_2151_p3 : Re_652_load_reg_3169);

assign Re_22_fu_2189_p3 = ((tmp_12_reg_3415[0:0] == 1'b1) ? srcR_38_fu_2177_p3 : Re_750_load_reg_3164);

assign Re_23_fu_2215_p3 = ((tmp_13_reg_3421[0:0] == 1'b1) ? srcR_39_fu_2203_p3 : Re_848_load_reg_3159);

assign Re_24_fu_2241_p3 = ((tmp_14_reg_3427[0:0] == 1'b1) ? srcR_40_fu_2229_p3 : Re_946_load_reg_3154);

assign Re_25_fu_2267_p3 = ((tmp_15_reg_3433[0:0] == 1'b1) ? srcR_41_fu_2255_p3 : Re_1044_load_reg_3149);

assign Re_26_fu_2293_p3 = ((tmp_16_reg_3439[0:0] == 1'b1) ? srcR_42_fu_2281_p3 : Re_1142_load_reg_3144);

assign Re_27_fu_2319_p3 = ((tmp_17_reg_3445[0:0] == 1'b1) ? srcR_43_fu_2307_p3 : Re_1240_load_reg_3139);

assign Re_28_fu_2345_p3 = ((tmp_18_reg_3451[0:0] == 1'b1) ? srcR_44_fu_2333_p3 : Re_1338_load_reg_3134);

assign Re_29_fu_2371_p3 = ((tmp_19_reg_3457[0:0] == 1'b1) ? srcR_45_fu_2359_p3 : Re_1436_load_reg_3129);

assign Re_30_fu_2397_p3 = ((tmp_20_reg_3463[0:0] == 1'b1) ? srcR_46_fu_2385_p3 : Re_1534_load_reg_3124);

assign Re_fu_2007_p3 = ((trunc_ln166_reg_3331[0:0] == 1'b1) ? srcR_31_fu_1995_p3 : Re64_load_reg_3199);

assign T3R1_address0 = zext_ln157_fu_1155_p1;

assign T3R2_address0 = zext_ln157_fu_1155_p1;

assign T4R1_address0 = zext_ln157_reg_2962;

assign T4R2_address0 = zext_ln157_fu_1155_p1;

assign T5R1_address0 = zext_ln157_reg_2962;

assign T5R2_address0 = zext_ln157_reg_2962;

assign TEMP1_address0 = zext_ln157_reg_2962;

assign TW_IM_address0 = zext_ln186_fu_1190_p1;

assign TW_RE_address0 = zext_ln186_fu_1190_p1;

assign add_ln126_1_fu_1647_p2 = ($signed(sext_ln126_2_fu_1640_p1) + $signed(sext_ln122_2_fu_1637_p1));

assign add_ln126_fu_1643_p2 = (trunc_ln126_reg_3275 + trunc_ln122_reg_3265);

assign add_ln127_fu_1682_p2 = ($signed(m3_reg_3255) + $signed(sext_ln127_fu_1679_p1));

assign ai_fu_1631_p3 = ((T4R1_q0[0:0] == 1'b1) ? varI2_reg_3219 : varI1_reg_3214);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign ar_fu_1625_p3 = ((T4R1_q0[0:0] == 1'b1) ? varR2_reg_3209 : varR1_reg_3204);

assign bi_fu_1551_p3 = ((T4R2_load_reg_3005[0:0] == 1'b1) ? varI2_fu_1481_p31 : varI1_fu_1418_p31);

assign br_fu_1544_p3 = ((T4R2_load_reg_3005[0:0] == 1'b1) ? varR2_fu_1355_p31 : varR1_fu_1292_p31);

assign ci_fu_1930_p3 = {{tmp_4_fu_1922_p3}, {trunc_ln87_2_fu_1918_p1}};

assign cr_fu_1869_p3 = {{tmp_2_fu_1861_p3}, {trunc_ln87_fu_1857_p1}};

assign di_fu_1959_p3 = {{tmp_5_fu_1951_p3}, {trunc_ln87_3_fu_1947_p1}};

assign dr_fu_1898_p3 = {{tmp_3_fu_1890_p3}, {trunc_ln87_1_fu_1886_p1}};

assign icmp_ln157_fu_1169_p2 = ((ap_sig_allocacmp_st65_load == 6'd32) ? 1'b1 : 1'b0);

assign m2_fu_1562_p2 = ($signed(17'd0) - $signed(sext_ln122_fu_1558_p1));

assign mul_ln122_fu_1592_p0 = sext_ln121_1_fu_1571_p1;

assign mul_ln127_fu_1615_p0 = sext_ln121_1_fu_1571_p1;

assign nextRe_32_out = ((tmp_6_reg_3379[0:0] == 1'b1) ? srcR_32_fu_2021_p3 : Re_162_load_reg_3194);

assign nextRe_33_out = ((tmp_7_reg_3385[0:0] == 1'b1) ? srcR_33_fu_2047_p3 : Re_260_load_reg_3189);

assign nextRe_34_out = ((tmp_8_reg_3391[0:0] == 1'b1) ? srcR_34_fu_2073_p3 : Re_358_load_reg_3184);

assign nextRe_35_out = ((tmp_9_reg_3397[0:0] == 1'b1) ? srcR_35_fu_2099_p3 : Re_456_load_reg_3179);

assign nextRe_36_out = ((tmp_10_reg_3403[0:0] == 1'b1) ? srcR_36_fu_2125_p3 : Re_554_load_reg_3174);

assign nextRe_37_out = ((tmp_11_reg_3409[0:0] == 1'b1) ? srcR_37_fu_2151_p3 : Re_652_load_reg_3169);

assign nextRe_38_out = ((tmp_12_reg_3415[0:0] == 1'b1) ? srcR_38_fu_2177_p3 : Re_750_load_reg_3164);

assign nextRe_39_out = ((tmp_13_reg_3421[0:0] == 1'b1) ? srcR_39_fu_2203_p3 : Re_848_load_reg_3159);

assign nextRe_40_out = ((tmp_14_reg_3427[0:0] == 1'b1) ? srcR_40_fu_2229_p3 : Re_946_load_reg_3154);

assign nextRe_41_out = ((tmp_15_reg_3433[0:0] == 1'b1) ? srcR_41_fu_2255_p3 : Re_1044_load_reg_3149);

assign nextRe_42_out = ((tmp_16_reg_3439[0:0] == 1'b1) ? srcR_42_fu_2281_p3 : Re_1142_load_reg_3144);

assign nextRe_43_out = ((tmp_17_reg_3445[0:0] == 1'b1) ? srcR_43_fu_2307_p3 : Re_1240_load_reg_3139);

assign nextRe_44_out = ((tmp_18_reg_3451[0:0] == 1'b1) ? srcR_44_fu_2333_p3 : Re_1338_load_reg_3134);

assign nextRe_45_out = ((tmp_19_reg_3457[0:0] == 1'b1) ? srcR_45_fu_2359_p3 : Re_1436_load_reg_3129);

assign nextRe_46_out = ((tmp_20_reg_3463[0:0] == 1'b1) ? srcR_46_fu_2385_p3 : Re_1534_load_reg_3124);

assign nextRe_out = ((trunc_ln166_reg_3331[0:0] == 1'b1) ? srcR_31_fu_1995_p3 : Re64_load_reg_3199);

assign p0i_fu_1981_p3 = ((T5R1_load_reg_3367[0:0] == 1'b1) ? di_fu_1959_p3 : ci_fu_1930_p3);

assign p0r_fu_1967_p3 = ((T5R1_load_reg_3367[0:0] == 1'b1) ? dr_fu_1898_p3 : cr_fu_1869_p3);

assign p1i_fu_1988_p3 = ((T5R2_load_reg_3373[0:0] == 1'b1) ? di_fu_1959_p3 : ci_fu_1930_p3);

assign p1r_fu_1974_p3 = ((T5R2_load_reg_3373[0:0] == 1'b1) ? dr_fu_1898_p3 : cr_fu_1869_p3);

assign sext_ln110_1_fu_1848_p1 = trunca1_reg_3347;

assign sext_ln110_2_fu_1877_p1 = $signed(trunca11_reg_3357);

assign sext_ln110_3_fu_1906_p1 = $signed(ai_reg_3342);

assign sext_ln110_4_fu_1909_p1 = trunca2_reg_3352;

assign sext_ln110_5_fu_1938_p1 = $signed(trunca21_reg_3362);

assign sext_ln110_fu_1845_p1 = $signed(ar_reg_3337);

assign sext_ln121_1_fu_1571_p1 = $signed(TW_RE_load_reg_3033);

assign sext_ln122_2_fu_1637_p1 = mul_ln122_reg_3260;

assign sext_ln122_fu_1558_p1 = bi_fu_1551_p3;

assign sext_ln126_2_fu_1640_p1 = mul_ln126_reg_3270;

assign sext_ln127_fu_1679_p1 = $signed(mul_ln127_reg_3280);

assign srcI_10_fu_2131_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0i_fu_1981_p3 : srcI_9);

assign srcI_12_fu_2157_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0i_fu_1981_p3 : srcI_11);

assign srcI_14_fu_2183_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1i_fu_1988_p3 : srcI_13);

assign srcI_16_fu_2209_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1i_fu_1988_p3 : srcI_15);

assign srcI_18_fu_2235_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0i_fu_1981_p3 : srcI_17);

assign srcI_20_fu_2261_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0i_fu_1981_p3 : srcI_19);

assign srcI_22_fu_2287_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1i_fu_1988_p3 : srcI_21);

assign srcI_24_fu_2313_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0i_fu_1981_p3 : srcI_23);

assign srcI_26_fu_2339_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1i_fu_1988_p3 : srcI_25);

assign srcI_28_fu_2365_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1i_fu_1988_p3 : srcI_27);

assign srcI_2_fu_2027_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1i_fu_1988_p3 : srcI_1);

assign srcI_30_fu_2391_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0i_fu_1981_p3 : srcI_29);

assign srcI_4_fu_2053_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1i_fu_1988_p3 : srcI_3);

assign srcI_6_fu_2079_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0i_fu_1981_p3 : srcI_5);

assign srcI_8_fu_2105_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1i_fu_1988_p3 : srcI_7);

assign srcI_fu_2001_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0i_fu_1981_p3 : Xi_load_15);

assign srcR_31_fu_1995_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0r_fu_1967_p3 : Xr_load_15);

assign srcR_32_fu_2021_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1r_fu_1974_p3 : srcR);

assign srcR_33_fu_2047_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1r_fu_1974_p3 : srcR_2);

assign srcR_34_fu_2073_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0r_fu_1967_p3 : srcR_4);

assign srcR_35_fu_2099_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1r_fu_1974_p3 : srcR_6);

assign srcR_36_fu_2125_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0r_fu_1967_p3 : srcR_8);

assign srcR_37_fu_2151_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0r_fu_1967_p3 : srcR_10);

assign srcR_38_fu_2177_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1r_fu_1974_p3 : srcR_12);

assign srcR_39_fu_2203_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1r_fu_1974_p3 : srcR_14);

assign srcR_40_fu_2229_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0r_fu_1967_p3 : srcR_16);

assign srcR_41_fu_2255_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0r_fu_1967_p3 : srcR_18);

assign srcR_42_fu_2281_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1r_fu_1974_p3 : srcR_20);

assign srcR_43_fu_2307_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0r_fu_1967_p3 : srcR_22);

assign srcR_44_fu_2333_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1r_fu_1974_p3 : srcR_24);

assign srcR_45_fu_2359_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p1r_fu_1974_p3 : srcR_26);

assign srcR_46_fu_2385_p3 = ((TEMP1_load_reg_3295[0:0] == 1'b1) ? p0r_fu_1967_p3 : srcR_28);

assign st_fu_1163_p2 = (ap_sig_allocacmp_st65_load + 6'd1);

assign sum_1_fu_1880_p2 = ($signed(sext_ln110_2_fu_1877_p1) + $signed(sext_ln110_fu_1845_p1));

assign sum_2_fu_1912_p2 = ($signed(sext_ln110_4_fu_1909_p1) + $signed(sext_ln110_3_fu_1906_p1));

assign sum_3_fu_1941_p2 = ($signed(sext_ln110_5_fu_1938_p1) + $signed(sext_ln110_3_fu_1906_p1));

assign sum_fu_1851_p2 = ($signed(sext_ln110_1_fu_1848_p1) + $signed(sext_ln110_fu_1845_p1));

assign tmp_1_fu_1697_p3 = add_ln127_fu_1682_p2[32'd30];

assign tmp_2_fu_1861_p3 = sum_fu_1851_p2[32'd16];

assign tmp_3_fu_1890_p3 = sum_1_fu_1880_p2[32'd16];

assign tmp_4_fu_1922_p3 = sum_2_fu_1912_p2[32'd16];

assign tmp_5_fu_1951_p3 = sum_3_fu_1941_p2[32'd16];

assign tmp_fu_1663_p3 = add_ln126_1_fu_1647_p2[32'd30];

assign trunc_ln102_1_fu_1687_p4 = {{add_ln127_fu_1682_p2[28:14]}};

assign trunc_ln122_fu_1598_p1 = mul_ln122_fu_1592_p2[28:0];

assign trunc_ln126_fu_1611_p1 = mul_ln126_fu_1605_p2[28:0];

assign trunc_ln166_fu_1621_p1 = HAB_q0[0:0];

assign trunc_ln1_fu_1653_p4 = {{add_ln126_fu_1643_p2[28:14]}};

assign trunc_ln87_1_fu_1886_p1 = sum_1_fu_1880_p2[14:0];

assign trunc_ln87_2_fu_1918_p1 = sum_2_fu_1912_p2[14:0];

assign trunc_ln87_3_fu_1947_p1 = sum_3_fu_1941_p2[14:0];

assign trunc_ln87_fu_1857_p1 = sum_fu_1851_p2[14:0];

assign trunca11_fu_1713_p2 = ($signed(16'd0) - $signed(trunca1_fu_1671_p3));

assign trunca1_fu_1671_p3 = {{tmp_fu_1663_p3}, {trunc_ln1_fu_1653_p4}};

assign trunca21_fu_1719_p2 = ($signed(16'd0) - $signed(trunca2_fu_1705_p3));

assign trunca2_fu_1705_p3 = {{tmp_1_fu_1697_p3}, {trunc_ln102_1_fu_1687_p4}};

assign varI1_fu_1418_p29 = 'bx;

assign varI2_fu_1481_p29 = 'bx;

assign varR1_fu_1292_p29 = 'bx;

assign varR2_fu_1355_p29 = 'bx;

assign zext_ln157_fu_1155_p1 = ap_sig_allocacmp_st65_load;

assign zext_ln166_fu_1180_p1 = T3R1_q0;

assign zext_ln167_fu_1185_p1 = T3R2_q0;

assign zext_ln186_fu_1190_p1 = ROM_ADDR_q0;

always @ (posedge ap_clk) begin
    zext_ln157_reg_2962[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2
