// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fft16_hls_fft16_hls,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.793000,HLS_SYN_LAT=153,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2605,HLS_SYN_LUT=2820,HLS_VERSION=2025_1}" *)

module fft16_hls (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Xr_address0,
        Xr_ce0,
        Xr_q0,
        Xr_address1,
        Xr_ce1,
        Xr_q1,
        Xi_address0,
        Xi_ce0,
        Xi_q0,
        Xi_address1,
        Xi_ce1,
        Xi_q1,
        outRe_address0,
        outRe_ce0,
        outRe_we0,
        outRe_d0,
        outRe_address1,
        outRe_ce1,
        outRe_we1,
        outRe_d1,
        outIm_address0,
        outIm_ce0,
        outIm_we0,
        outIm_d0,
        outIm_address1,
        outIm_ce1,
        outIm_we1,
        outIm_d1
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] Xr_address0;
output   Xr_ce0;
input  [15:0] Xr_q0;
output  [3:0] Xr_address1;
output   Xr_ce1;
input  [15:0] Xr_q1;
output  [3:0] Xi_address0;
output   Xi_ce0;
input  [15:0] Xi_q0;
output  [3:0] Xi_address1;
output   Xi_ce1;
input  [15:0] Xi_q1;
output  [3:0] outRe_address0;
output   outRe_ce0;
output   outRe_we0;
output  [15:0] outRe_d0;
output  [3:0] outRe_address1;
output   outRe_ce1;
output   outRe_we1;
output  [15:0] outRe_d1;
output  [3:0] outIm_address0;
output   outIm_ce0;
output   outIm_we0;
output  [15:0] outIm_d0;
output  [3:0] outIm_address1;
output   outIm_ce1;
output   outIm_we1;
output  [15:0] outIm_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] Xr_load_reg_1262;
wire    ap_CS_fsm_state2;
reg   [15:0] Xi_load_reg_1267;
reg   [15:0] Xr_load_1_reg_1272;
reg   [15:0] Xi_load_1_reg_1277;
reg   [15:0] Xr_load_2_reg_1302;
wire    ap_CS_fsm_state3;
reg   [15:0] Xi_load_2_reg_1307;
reg   [15:0] Xr_load_3_reg_1312;
reg   [15:0] Xi_load_3_reg_1317;
reg   [15:0] Xr_load_4_reg_1342;
wire    ap_CS_fsm_state4;
reg   [15:0] Xi_load_4_reg_1347;
reg   [15:0] Xr_load_5_reg_1352;
reg   [15:0] Xi_load_5_reg_1357;
reg   [15:0] Xr_load_6_reg_1382;
wire    ap_CS_fsm_state5;
reg   [15:0] Xi_load_6_reg_1387;
reg   [15:0] Xr_load_7_reg_1392;
reg   [15:0] Xi_load_7_reg_1397;
reg   [15:0] Xr_load_8_reg_1422;
wire    ap_CS_fsm_state6;
reg   [15:0] Xi_load_8_reg_1427;
reg   [15:0] Xr_load_9_reg_1432;
reg   [15:0] Xi_load_9_reg_1437;
reg   [15:0] Xr_load_10_reg_1462;
wire    ap_CS_fsm_state7;
reg   [15:0] Xi_load_10_reg_1467;
reg   [15:0] Xr_load_11_reg_1472;
reg   [15:0] Xi_load_11_reg_1477;
reg   [15:0] Xr_load_12_reg_1502;
wire    ap_CS_fsm_state8;
reg   [15:0] Xi_load_12_reg_1507;
reg   [15:0] Xr_load_13_reg_1512;
reg   [15:0] Xi_load_13_reg_1517;
reg   [15:0] Xr_load_14_reg_1542;
wire    ap_CS_fsm_state9;
reg   [15:0] Xi_load_14_reg_1547;
reg   [15:0] Xr_load_15_reg_1552;
reg   [15:0] Xi_load_15_reg_1557;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_idle;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_ready;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out_ap_vld;
wire   [15:0] grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out;
wire    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out_ap_vld;
reg    grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg;
wire    ap_CS_fsm_state10;
reg   [15:0] nextRe_loc_fu_208;
reg   [15:0] Im_16_loc_fu_204;
reg   [15:0] nextRe_32_loc_fu_200;
reg   [15:0] Im_17_loc_fu_196;
reg   [15:0] nextRe_33_loc_fu_192;
reg   [15:0] Im_18_loc_fu_188;
reg   [15:0] nextRe_34_loc_fu_184;
reg   [15:0] Im_19_loc_fu_180;
reg   [15:0] nextRe_35_loc_fu_176;
reg   [15:0] Im_20_loc_fu_172;
reg   [15:0] nextRe_36_loc_fu_168;
reg   [15:0] Im_21_loc_fu_164;
reg   [15:0] nextRe_37_loc_fu_160;
reg   [15:0] Im_22_loc_fu_156;
reg   [15:0] nextRe_38_loc_fu_152;
reg   [15:0] Im_23_loc_fu_148;
reg   [15:0] nextRe_39_loc_fu_144;
reg   [15:0] Im_24_loc_fu_140;
reg   [15:0] nextRe_40_loc_fu_136;
reg   [15:0] Im_25_loc_fu_132;
reg   [15:0] nextRe_41_loc_fu_128;
reg   [15:0] Im_26_loc_fu_124;
reg   [15:0] nextRe_42_loc_fu_120;
reg   [15:0] Im_27_loc_fu_116;
reg   [15:0] nextRe_43_loc_fu_112;
reg   [15:0] Im_28_loc_fu_108;
reg   [15:0] nextRe_44_loc_fu_104;
reg   [15:0] Im_29_loc_fu_100;
reg   [15:0] nextRe_45_loc_fu_96;
reg   [15:0] Im_30_loc_fu_92;
reg   [15:0] nextRe_46_loc_fu_88;
reg   [15:0] Im_31_loc_fu_84;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
reg    Xr_ce1_local;
reg   [3:0] Xr_address1_local;
reg    Xr_ce0_local;
reg   [3:0] Xr_address0_local;
reg    Xi_ce1_local;
reg   [3:0] Xi_address1_local;
reg    Xi_ce0_local;
reg   [3:0] Xi_address0_local;
reg    outRe_we1_local;
reg   [15:0] outRe_d1_local;
reg    outRe_ce1_local;
reg   [3:0] outRe_address1_local;
reg    outRe_we0_local;
reg   [15:0] outRe_d0_local;
reg    outRe_ce0_local;
reg   [3:0] outRe_address0_local;
reg    outIm_we1_local;
reg   [15:0] outIm_d1_local;
reg    outIm_ce1_local;
reg   [3:0] outIm_address1_local;
reg    outIm_we0_local;
reg   [15:0] outIm_d0_local;
reg    outIm_ce0_local;
reg   [3:0] outIm_address0_local;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg = 1'b0;
end

fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2 grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start),
    .ap_done(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done),
    .ap_idle(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_idle),
    .ap_ready(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_ready),
    .Xr_load_15(Xr_load_15_reg_1552),
    .Xi_load_15(Xi_load_15_reg_1557),
    .srcR(Xr_load_reg_1262),
    .srcI_1(Xi_load_reg_1267),
    .srcR_2(Xr_load_1_reg_1272),
    .srcI_3(Xi_load_1_reg_1277),
    .srcR_4(Xr_load_2_reg_1302),
    .srcI_5(Xi_load_2_reg_1307),
    .srcR_6(Xr_load_3_reg_1312),
    .srcI_7(Xi_load_3_reg_1317),
    .srcR_8(Xr_load_4_reg_1342),
    .srcI_9(Xi_load_4_reg_1347),
    .srcR_10(Xr_load_5_reg_1352),
    .srcI_11(Xi_load_5_reg_1357),
    .srcR_12(Xr_load_6_reg_1382),
    .srcI_13(Xi_load_6_reg_1387),
    .srcR_14(Xr_load_7_reg_1392),
    .srcI_15(Xi_load_7_reg_1397),
    .srcR_16(Xr_load_8_reg_1422),
    .srcI_17(Xi_load_8_reg_1427),
    .srcR_18(Xr_load_9_reg_1432),
    .srcI_19(Xi_load_9_reg_1437),
    .srcR_20(Xr_load_10_reg_1462),
    .srcI_21(Xi_load_10_reg_1467),
    .srcR_22(Xr_load_11_reg_1472),
    .srcI_23(Xi_load_11_reg_1477),
    .srcR_24(Xr_load_12_reg_1502),
    .srcI_25(Xi_load_12_reg_1507),
    .srcR_26(Xr_load_13_reg_1512),
    .srcI_27(Xi_load_13_reg_1517),
    .srcR_28(Xr_load_14_reg_1542),
    .srcI_29(Xi_load_14_reg_1547),
    .nextRe_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out),
    .nextRe_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out_ap_vld),
    .Im_16_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out),
    .Im_16_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out_ap_vld),
    .nextRe_32_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out),
    .nextRe_32_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out_ap_vld),
    .Im_17_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out),
    .Im_17_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out_ap_vld),
    .nextRe_33_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out),
    .nextRe_33_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out_ap_vld),
    .Im_18_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out),
    .Im_18_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out_ap_vld),
    .nextRe_34_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out),
    .nextRe_34_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out_ap_vld),
    .Im_19_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out),
    .Im_19_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out_ap_vld),
    .nextRe_35_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out),
    .nextRe_35_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out_ap_vld),
    .Im_20_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out),
    .Im_20_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out_ap_vld),
    .nextRe_36_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out),
    .nextRe_36_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out_ap_vld),
    .Im_21_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out),
    .Im_21_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out_ap_vld),
    .nextRe_37_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out),
    .nextRe_37_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out_ap_vld),
    .Im_22_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out),
    .Im_22_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out_ap_vld),
    .nextRe_38_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out),
    .nextRe_38_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out_ap_vld),
    .Im_23_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out),
    .Im_23_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out_ap_vld),
    .nextRe_39_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out),
    .nextRe_39_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out_ap_vld),
    .Im_24_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out),
    .Im_24_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out_ap_vld),
    .nextRe_40_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out),
    .nextRe_40_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out_ap_vld),
    .Im_25_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out),
    .Im_25_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out_ap_vld),
    .nextRe_41_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out),
    .nextRe_41_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out_ap_vld),
    .Im_26_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out),
    .Im_26_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out_ap_vld),
    .nextRe_42_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out),
    .nextRe_42_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out_ap_vld),
    .Im_27_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out),
    .Im_27_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out_ap_vld),
    .nextRe_43_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out),
    .nextRe_43_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out_ap_vld),
    .Im_28_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out),
    .Im_28_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out_ap_vld),
    .nextRe_44_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out),
    .nextRe_44_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out_ap_vld),
    .Im_29_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out),
    .Im_29_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out_ap_vld),
    .nextRe_45_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out),
    .nextRe_45_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out_ap_vld),
    .Im_30_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out),
    .Im_30_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out_ap_vld),
    .nextRe_46_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out),
    .nextRe_46_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out_ap_vld),
    .Im_31_out(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out),
    .Im_31_out_ap_vld(grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg <= 1'b1;
        end else if ((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_ready == 1'b1)) begin
            grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_16_loc_fu_204 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_16_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_17_loc_fu_196 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_17_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_18_loc_fu_188 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_18_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_19_loc_fu_180 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_19_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_20_loc_fu_172 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_20_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_21_loc_fu_164 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_21_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_22_loc_fu_156 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_22_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_23_loc_fu_148 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_23_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_24_loc_fu_140 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_24_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_25_loc_fu_132 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_25_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_26_loc_fu_124 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_26_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_27_loc_fu_116 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_27_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_28_loc_fu_108 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_28_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_29_loc_fu_100 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_29_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_30_loc_fu_92 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_30_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Im_31_loc_fu_84 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_Im_31_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Xi_load_10_reg_1467 <= Xi_q1;
        Xi_load_11_reg_1477 <= Xi_q0;
        Xr_load_10_reg_1462 <= Xr_q1;
        Xr_load_11_reg_1472 <= Xr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Xi_load_12_reg_1507 <= Xi_q1;
        Xi_load_13_reg_1517 <= Xi_q0;
        Xr_load_12_reg_1502 <= Xr_q1;
        Xr_load_13_reg_1512 <= Xr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Xi_load_14_reg_1547 <= Xi_q1;
        Xi_load_15_reg_1557 <= Xi_q0;
        Xr_load_14_reg_1542 <= Xr_q1;
        Xr_load_15_reg_1552 <= Xr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Xi_load_1_reg_1277 <= Xi_q0;
        Xi_load_reg_1267 <= Xi_q1;
        Xr_load_1_reg_1272 <= Xr_q0;
        Xr_load_reg_1262 <= Xr_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Xi_load_2_reg_1307 <= Xi_q1;
        Xi_load_3_reg_1317 <= Xi_q0;
        Xr_load_2_reg_1302 <= Xr_q1;
        Xr_load_3_reg_1312 <= Xr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Xi_load_4_reg_1347 <= Xi_q1;
        Xi_load_5_reg_1357 <= Xi_q0;
        Xr_load_4_reg_1342 <= Xr_q1;
        Xr_load_5_reg_1352 <= Xr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Xi_load_6_reg_1387 <= Xi_q1;
        Xi_load_7_reg_1397 <= Xi_q0;
        Xr_load_6_reg_1382 <= Xr_q1;
        Xr_load_7_reg_1392 <= Xr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Xi_load_8_reg_1427 <= Xi_q1;
        Xi_load_9_reg_1437 <= Xi_q0;
        Xr_load_8_reg_1422 <= Xr_q1;
        Xr_load_9_reg_1432 <= Xr_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_32_loc_fu_200 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_32_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_33_loc_fu_192 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_33_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_34_loc_fu_184 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_34_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_35_loc_fu_176 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_35_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_36_loc_fu_168 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_36_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_37_loc_fu_160 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_37_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_38_loc_fu_152 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_38_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_39_loc_fu_144 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_39_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_40_loc_fu_136 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_40_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_41_loc_fu_128 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_41_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_42_loc_fu_120 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_42_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_43_loc_fu_112 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_43_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_44_loc_fu_104 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_44_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_45_loc_fu_96 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_45_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_46_loc_fu_88 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_46_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nextRe_loc_fu_208 <= grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_nextRe_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Xi_address0_local = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        Xi_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        Xi_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        Xi_address0_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Xi_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        Xi_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Xi_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        Xi_address0_local = 64'd2;
    end else begin
        Xi_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Xi_address1_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        Xi_address1_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        Xi_address1_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        Xi_address1_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Xi_address1_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        Xi_address1_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Xi_address1_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        Xi_address1_local = 64'd1;
    end else begin
        Xi_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        Xi_ce0_local = 1'b1;
    end else begin
        Xi_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        Xi_ce1_local = 1'b1;
    end else begin
        Xi_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Xr_address0_local = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        Xr_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        Xr_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        Xr_address0_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Xr_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        Xr_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Xr_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        Xr_address0_local = 64'd2;
    end else begin
        Xr_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Xr_address1_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        Xr_address1_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        Xr_address1_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        Xr_address1_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Xr_address1_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        Xr_address1_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Xr_address1_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        Xr_address1_local = 64'd1;
    end else begin
        Xr_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        Xr_ce0_local = 1'b1;
    end else begin
        Xr_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        Xr_ce1_local = 1'b1;
    end else begin
        Xr_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        outIm_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        outIm_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        outIm_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outIm_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        outIm_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        outIm_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outIm_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        outIm_address0_local = 64'd1;
    end else begin
        outIm_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        outIm_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        outIm_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        outIm_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outIm_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        outIm_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        outIm_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outIm_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        outIm_address1_local = 64'd0;
    end else begin
        outIm_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        outIm_ce0_local = 1'b1;
    end else begin
        outIm_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        outIm_ce1_local = 1'b1;
    end else begin
        outIm_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        outIm_d0_local = Im_31_loc_fu_84;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        outIm_d0_local = Im_27_loc_fu_116;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        outIm_d0_local = Im_29_loc_fu_100;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outIm_d0_local = Im_25_loc_fu_132;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        outIm_d0_local = Im_30_loc_fu_92;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        outIm_d0_local = Im_26_loc_fu_124;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outIm_d0_local = Im_28_loc_fu_108;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        outIm_d0_local = Im_24_loc_fu_140;
    end else begin
        outIm_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        outIm_d1_local = Im_23_loc_fu_148;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        outIm_d1_local = Im_19_loc_fu_180;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        outIm_d1_local = Im_21_loc_fu_164;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outIm_d1_local = Im_17_loc_fu_196;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        outIm_d1_local = Im_22_loc_fu_156;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        outIm_d1_local = Im_18_loc_fu_188;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outIm_d1_local = Im_20_loc_fu_172;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        outIm_d1_local = Im_16_loc_fu_204;
    end else begin
        outIm_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        outIm_we0_local = 1'b1;
    end else begin
        outIm_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        outIm_we1_local = 1'b1;
    end else begin
        outIm_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        outRe_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        outRe_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        outRe_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outRe_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        outRe_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        outRe_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outRe_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        outRe_address0_local = 64'd1;
    end else begin
        outRe_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        outRe_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        outRe_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        outRe_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outRe_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        outRe_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        outRe_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outRe_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        outRe_address1_local = 64'd0;
    end else begin
        outRe_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        outRe_ce0_local = 1'b1;
    end else begin
        outRe_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        outRe_ce1_local = 1'b1;
    end else begin
        outRe_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        outRe_d0_local = nextRe_46_loc_fu_88;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        outRe_d0_local = nextRe_42_loc_fu_120;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        outRe_d0_local = nextRe_44_loc_fu_104;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outRe_d0_local = nextRe_40_loc_fu_136;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        outRe_d0_local = nextRe_45_loc_fu_96;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        outRe_d0_local = nextRe_41_loc_fu_128;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outRe_d0_local = nextRe_43_loc_fu_112;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        outRe_d0_local = nextRe_39_loc_fu_144;
    end else begin
        outRe_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        outRe_d1_local = nextRe_38_loc_fu_152;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        outRe_d1_local = nextRe_34_loc_fu_184;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        outRe_d1_local = nextRe_36_loc_fu_168;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outRe_d1_local = nextRe_32_loc_fu_200;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        outRe_d1_local = nextRe_37_loc_fu_160;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        outRe_d1_local = nextRe_33_loc_fu_192;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        outRe_d1_local = nextRe_35_loc_fu_176;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        outRe_d1_local = nextRe_loc_fu_208;
    end else begin
        outRe_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        outRe_we0_local = 1'b1;
    end else begin
        outRe_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        outRe_we1_local = 1'b1;
    end else begin
        outRe_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Xi_address0 = Xi_address0_local;

assign Xi_address1 = Xi_address1_local;

assign Xi_ce0 = Xi_ce0_local;

assign Xi_ce1 = Xi_ce1_local;

assign Xr_address0 = Xr_address0_local;

assign Xr_address1 = Xr_address1_local;

assign Xr_ce0 = Xr_ce0_local;

assign Xr_ce1 = Xr_ce1_local;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start = grp_fft16_hls_Pipeline_VITIS_LOOP_157_2_fu_824_ap_start_reg;

assign outIm_address0 = outIm_address0_local;

assign outIm_address1 = outIm_address1_local;

assign outIm_ce0 = outIm_ce0_local;

assign outIm_ce1 = outIm_ce1_local;

assign outIm_d0 = outIm_d0_local;

assign outIm_d1 = outIm_d1_local;

assign outIm_we0 = outIm_we0_local;

assign outIm_we1 = outIm_we1_local;

assign outRe_address0 = outRe_address0_local;

assign outRe_address1 = outRe_address1_local;

assign outRe_ce0 = outRe_ce0_local;

assign outRe_ce1 = outRe_ce1_local;

assign outRe_d0 = outRe_d0_local;

assign outRe_d1 = outRe_d1_local;

assign outRe_we0 = outRe_we0_local;

assign outRe_we1 = outRe_we1_local;

endmodule //fft16_hls
