# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "F:/github_projects/codigo_modificado_c_ferreirinha/codigo_modificado_c_ferreirinha/codigo_modificado_c_ferreirinha.runs/synth_1/fft16_hls.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/github_projects/codigo_modificado_c_ferreirinha/codigo_modificado_c_ferreirinha/codigo_modificado_c_ferreirinha.cache/wt [current_project]
set_property parent.project_path F:/github_projects/codigo_modificado_c_ferreirinha/codigo_modificado_c_ferreirinha/codigo_modificado_c_ferreirinha.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/github_projects/codigo_modificado_c_ferreirinha/codigo_modificado_c_ferreirinha/codigo_modificado_c_ferreirinha.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_HAB_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_MUX_A_IDX_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_MUX_B_IDX_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_ROM_ADDR_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T3R1_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T3R2_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T4R1_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T4R2_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_TEMP1_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_TW_IM_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_TW_RE_ROM_AUTO_1R.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_flow_control_loop_pipe_sequential_init.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_mul_15s_16s_31_1_1.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_mul_15s_17s_30_1_1.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_mul_16s_16s_30_1_1.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls_sparsemux_29_4_16_1_1.vhd
  F:/github_projects/codigo_modificado_c_ferreirinha/fft16_hls.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fft16_hls -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fft16_hls.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file fft16_hls_utilization_synth.rpt -pb fft16_hls_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
