-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity radix2_realinhamento is
port (
    Ar : IN STD_LOGIC_VECTOR (15 downto 0);
    Ai : IN STD_LOGIC_VECTOR (15 downto 0);
    Br : IN STD_LOGIC_VECTOR (15 downto 0);
    Bi : IN STD_LOGIC_VECTOR (15 downto 0);
    Wr : IN STD_LOGIC_VECTOR (15 downto 0);
    Wi : IN STD_LOGIC_VECTOR (15 downto 0);
    Cr : OUT STD_LOGIC_VECTOR (15 downto 0);
    Dr : OUT STD_LOGIC_VECTOR (15 downto 0);
    Ci : OUT STD_LOGIC_VECTOR (15 downto 0);
    Di : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of radix2_realinhamento is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "radix2_realinhamento_radix2_realinhamento,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.848937,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=216,HLS_VERSION=2025_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal m1_fu_132_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln52_1_fu_128_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal m1_fu_132_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln52_fu_124_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal m2_fu_146_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln53_1_fu_142_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal m2_fu_146_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln53_fu_138_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal m3_fu_152_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal m3_fu_152_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal m4_fu_158_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal m4_fu_158_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal m1_fu_132_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_164_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_172_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal m2_fu_146_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_188_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_196_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal m3_fu_152_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_212_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_220_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal m4_fu_158_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_236_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_244_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal t1_fu_180_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal t2_fu_204_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln62_1_fu_264_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln62_fu_260_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln62_fu_272_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln62_3_fu_278_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln62_2_fu_268_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln63_fu_288_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln63_fu_294_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal t3_fu_228_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal t4_fu_252_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln64_fu_304_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln64_4_fu_320_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln64_fu_324_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln64_5_fu_330_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln64_1_fu_308_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln64_3_fu_312_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln65_fu_340_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln65_fu_346_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln64_2_fu_316_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal cr_sum_fu_282_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_6_fu_356_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln20_fu_364_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal dr_sum_fu_298_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_8_fu_377_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln20_1_fu_385_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ci_sum_fu_334_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_9_fu_398_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln20_2_fu_406_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal di_sum_fu_350_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_10_fu_419_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln20_3_fu_427_p1 : STD_LOGIC_VECTOR (14 downto 0);

    component radix2_realinhamento_mul_16s_16s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mul_16s_16s_32_1_1_U1 : component radix2_realinhamento_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => m1_fu_132_p0,
        din1 => m1_fu_132_p1,
        dout => m1_fu_132_p2);

    mul_16s_16s_32_1_1_U2 : component radix2_realinhamento_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => m2_fu_146_p0,
        din1 => m2_fu_146_p1,
        dout => m2_fu_146_p2);

    mul_16s_16s_32_1_1_U3 : component radix2_realinhamento_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => m3_fu_152_p0,
        din1 => m3_fu_152_p1,
        dout => m3_fu_152_p2);

    mul_16s_16s_32_1_1_U4 : component radix2_realinhamento_mul_16s_16s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => m4_fu_158_p0,
        din1 => m4_fu_158_p1,
        dout => m4_fu_158_p2);




    Ci <= (tmp_9_fu_398_p3 & trunc_ln20_2_fu_406_p1);
    Cr <= (tmp_6_fu_356_p3 & trunc_ln20_fu_364_p1);
    Di <= (tmp_10_fu_419_p3 & trunc_ln20_3_fu_427_p1);
    Dr <= (tmp_8_fu_377_p3 & trunc_ln20_1_fu_385_p1);
    add_ln62_fu_272_p2 <= std_logic_vector(signed(sext_ln62_1_fu_264_p1) + signed(sext_ln62_fu_260_p1));
    add_ln64_fu_324_p2 <= std_logic_vector(signed(sext_ln64_fu_304_p1) + signed(sext_ln64_4_fu_320_p1));
    ci_sum_fu_334_p2 <= std_logic_vector(signed(sext_ln64_5_fu_330_p1) + signed(sext_ln64_1_fu_308_p1));
    cr_sum_fu_282_p2 <= std_logic_vector(signed(sext_ln62_3_fu_278_p1) - signed(sext_ln62_2_fu_268_p1));
    di_sum_fu_350_p2 <= std_logic_vector(signed(sext_ln65_fu_346_p1) - signed(sext_ln64_2_fu_316_p1));
    dr_sum_fu_298_p2 <= std_logic_vector(signed(sext_ln63_fu_294_p1) + signed(sext_ln62_2_fu_268_p1));
    m1_fu_132_p0 <= sext_ln52_1_fu_128_p1(16 - 1 downto 0);
    m1_fu_132_p1 <= sext_ln52_fu_124_p1(16 - 1 downto 0);
    m2_fu_146_p0 <= sext_ln53_1_fu_142_p1(16 - 1 downto 0);
    m2_fu_146_p1 <= sext_ln53_fu_138_p1(16 - 1 downto 0);
    m3_fu_152_p0 <= sext_ln53_1_fu_142_p1(16 - 1 downto 0);
    m3_fu_152_p1 <= sext_ln52_fu_124_p1(16 - 1 downto 0);
    m4_fu_158_p0 <= sext_ln52_1_fu_128_p1(16 - 1 downto 0);
    m4_fu_158_p1 <= sext_ln53_fu_138_p1(16 - 1 downto 0);
        sext_ln52_1_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Wr),32));

        sext_ln52_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Br),32));

        sext_ln53_1_fu_142_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Wi),32));

        sext_ln53_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Bi),32));

        sext_ln62_1_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t1_fu_180_p3),17));

        sext_ln62_2_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t2_fu_204_p3),18));

        sext_ln62_3_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln62_fu_272_p2),18));

        sext_ln62_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ar),17));

        sext_ln63_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln63_fu_288_p2),18));

        sext_ln64_1_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t3_fu_228_p3),18));

        sext_ln64_2_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t4_fu_252_p3),18));

        sext_ln64_3_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t3_fu_228_p3),17));

        sext_ln64_4_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(t4_fu_252_p3),17));

        sext_ln64_5_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln64_fu_324_p2),18));

        sext_ln64_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ai),17));

        sext_ln65_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln65_fu_340_p2),18));

    sub_ln63_fu_288_p2 <= std_logic_vector(signed(sext_ln62_fu_260_p1) - signed(sext_ln62_1_fu_264_p1));
    sub_ln65_fu_340_p2 <= std_logic_vector(signed(sext_ln64_fu_304_p1) - signed(sext_ln64_3_fu_312_p1));
    t1_fu_180_p3 <= (tmp_fu_164_p3 & tmp_1_fu_172_p3);
    t2_fu_204_p3 <= (tmp_2_fu_188_p3 & tmp_4_fu_196_p3);
    t3_fu_228_p3 <= (tmp_3_fu_212_p3 & tmp_7_fu_220_p3);
    t4_fu_252_p3 <= (tmp_5_fu_236_p3 & tmp_s_fu_244_p3);
    tmp_10_fu_419_p3 <= di_sum_fu_350_p2(17 downto 17);
    tmp_1_fu_172_p3 <= m1_fu_132_p2(28 downto 14);
    tmp_2_fu_188_p3 <= m2_fu_146_p2(31 downto 31);
    tmp_3_fu_212_p3 <= m3_fu_152_p2(31 downto 31);
    tmp_4_fu_196_p3 <= m2_fu_146_p2(28 downto 14);
    tmp_5_fu_236_p3 <= m4_fu_158_p2(31 downto 31);
    tmp_6_fu_356_p3 <= cr_sum_fu_282_p2(17 downto 17);
    tmp_7_fu_220_p3 <= m3_fu_152_p2(28 downto 14);
    tmp_8_fu_377_p3 <= dr_sum_fu_298_p2(17 downto 17);
    tmp_9_fu_398_p3 <= ci_sum_fu_334_p2(17 downto 17);
    tmp_fu_164_p3 <= m1_fu_132_p2(31 downto 31);
    tmp_s_fu_244_p3 <= m4_fu_158_p2(28 downto 14);
    trunc_ln20_1_fu_385_p1 <= dr_sum_fu_298_p2(15 - 1 downto 0);
    trunc_ln20_2_fu_406_p1 <= ci_sum_fu_334_p2(15 - 1 downto 0);
    trunc_ln20_3_fu_427_p1 <= di_sum_fu_350_p2(15 - 1 downto 0);
    trunc_ln20_fu_364_p1 <= cr_sum_fu_282_p2(15 - 1 downto 0);
end behav;
