-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T4R1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 1; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 33
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of fft16_hls_fft16_hls_Pipeline_VITIS_LOOP_157_2_T4R1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0", 1 => "0", 2 => "1", 3 => "1", 
    4 => "0", 5 => "1", 6 => "0", 7 => "0", 
    8 => "1", 9 => "0", 10 => "1", 11 => "1", 
    12 => "0", 13 => "1", 14 => "0", 15 => "0", 
    16 => "1", 17 => "0", 18 => "1", 19 => "1", 
    20 => "0", 21 => "1", 22 => "0", 23 => "0", 
    24 => "1", 25 => "0", 26 => "1", 27 => "1", 
    28 => "0", 29 => "1", 30 => "0", 31 => "0", 
    32 => "1");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

